### ISSUE TITLE
Search temporarily not working on fumadocs.vercel.app

### ISSUE THREAD

**Issue by anuragmitra4** [fuma-nama/fumadocs#1006]
### To Reproduce

This is not affecting my own deployment but search seems to be not working on the fumadocs.vercel.app website. To reproduce, go to fumadocs.vercel.app & search for anything using the search box.

### Current vs. Expected behavior

Expected behavior is to see a list of relevant search results. Currently see no results for any search terms. Here's a video:

https://github.com/user-attachments/assets/83869667-4a32-49ab-97b2-e8cae0be0361

### Provide environment information

```bash
Running the fumadocs.vercel.app on MacOS 15.1, Arc Browser (v1.66.0).
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

The same problem seems to exist also on Chrome.

**Comment by fuma-nama** [comment]
Algolia free tier limit exceeded, we will migrate to Orama Cloud soon
