### ISSUE TITLE
Auto Type Table should respect typescript alias in `tsconfig.json`

### ISSUE THREAD

**Issue by himself65** [fuma-nama/fumadocs#1017]
### What problem will this feature address?

as title, for now I read the source code it's just `fs.readFile(path)`. However, in my code it's a huge monorepo and it's pretty hard to maintain to use relative path

### Describe the solution you'd like

```json
    "paths": {
      "@/*": ["./src/*"]
    },
```

```mdx
<AutoTypeTable path="@/type.ts" name="HandlerContext" />
```

### Describe alternatives you've considered

I have to add my wrapper

```tsx
const { AutoTypeTable: Internal } = createTypeTable();

const AutoTypeTable = (props) => <Internal {...props} path={...}/>
```

**Comment by fuma-nama** [comment]
The path property is the file path of ts file, not an import path. It is required because we need to manipulate the file content and to improve performance by not scanning every file to Typescript Compiler.

**Comment by fuma-nama** [comment]
Also have you tried `type`? It's probably what you're looking for.

https://fumadocs.vercel.app/docs/ui/components/auto-type-table#type
