### ISSUE TITLE
Show ctrl instead of command for the search bar on windows

### ISSUE THREAD

**Issue by weikequ** [fuma-nama/fumadocs#1020]
### To Reproduce

1. Go to https://fumadocs.vercel.app/ on windows
2. See that the search hotkey is still cmd K

### Current vs. Expected behavior

The search shortcut should be changed to ctrl on windows instead of the command symbol.

### Provide environment information

```bash
Windows
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
I avoided that as it causes layout shifts, will add an option for that later.

**Comment by fuma-nama** [comment]
Updated, it should be working now

https://fumadocs-dev.vercel.app
