### ISSUE TITLE
hideLocale configuration not working with default-locale setting in Next.js app router

### ISSUE THREAD

**Issue by zjy365** [fuma-nama/fumadocs#1035]
### To Reproduce

The `hideLocale` configuration in my Next.js app router i18n setup is not working as expected when set to `'default-locale'`. The URL behavior for the default language is not being handled correctly.

### Current Configuration

Project structure:
```
./app
├── (home)
│   └── page.tsx
├── [lang]
│   └── docs
│       ├── [[...slug]]
│       │   └── page.tsx
│       └── layout.tsx
├── i18n.ts
└── ...
```

i18n configuration (`app/i18n.ts`):
```typescript
export const i18n: I18nConfig = {
  defaultLanguage: 'en',
  languages: LANGUAGES,
  hideLocale: 'default-locale',
};
```

### Expected Behavior
- URLs for the default language (en) should NOT include the locale prefix
- URLs for other languages should include the locale prefix

For example:
- `/docs/getting-started` (for English content)
- `/zh/docs/getting-started` (for Chinese content)

### Actual Behavior
The locale prefix is not being handled according to the `hideLocale: 'default-locale'` setting.

### Provide environment information

```bash
"fumadocs-core": "14.0.0",
    "fumadocs-mdx": "^11.1.0",
    "fumadocs-ui": "14.0.0",
    "next": "^14.2.8",
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
All pages must be living under the [lang] folder, we only hid the prefix but it actually exists on server side.

**Comment by zjy365** [comment]
```
./app
├── [lang]
│   ├── docs
│   │   ├── [[...slug]]
│   │   │   └── page.tsx
│   │   └── layout.tsx
│   ├── global.css
│   ├── layout.tsx
│   └── page.tsx
├── api
│   └── search
│       └── route.ts
├── i18n.ts
├── layout.config.tsx
└── source.ts
```

I adjusted the directory and it still doesn't work, can you give me some advice?

**Comment by zjy365** [comment]
Let me create a sandbox to test it.
