### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by Jay-Karia** [fuma-nama/fumadocs#1037]
### What problem will this feature address?

Adds linter and formatter

### Describe the solution you'd like

Add 2 more options in the CLI to include ESLint and Prettier

### Describe alternatives you've considered

N/A

**Comment by fuma-nama** [comment]
Your feature request lacks details, could you elaborate more?

**Comment by Jay-Karia** [comment]
We can add an option to add ESLint and Prettier in the project through CLI by prompting two questions.

Then we can setup ESLint (if allowed):
- installing required dev deps
- creating the config file and adding recommended config
- adding new script to run linting

Same we can do with Prettier.

**Comment by fuma-nama** [comment]
Prettier doesn't need a config, I prefer user land configuration. A default ESLint config is good, plus it is also worth noting that Next.js has its own lint process during production build.

**Comment by Jay-Karia** [comment]
So can we do something like this:

ESLint:
- install dev deps
- add `.eslintrc.json` file and
```json
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
```
- add script: `next lint`

Prettier:
- install dev deps
- add script: `npx prettier . --write`

**Comment by fuma-nama** [comment]
1. Next.js handles lint already, no need for script.
2. No, I still prefer user land formator configurations

**Comment by Jay-Karia** [comment]
ESLint:
- install dev deps
- add `.eslintrc.json` file and
```json
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
```

?
