### ISSUE TITLE
Error while in production 

### ISSUE THREAD

**Issue by Gitstar-OC** [fuma-nama/fumadocs#1057]
### To Reproduce

Production Only!

### Current vs. Expected behavior

![image](https://github.com/user-attachments/assets/a6023e41-3cb6-4d5b-9f71-57aad52c1de5)

This issue is coming with all of my sites where I am using fumadocs. All of the errors are due to the same reason. 
![image](https://github.com/user-attachments/assets/15400e51-d9ac-494d-9ad7-64b71e8fb031)

Everything seems to be fine in development but it is being shown in production only. 

![image](https://github.com/user-attachments/assets/53dd0148-be9f-45a3-b5e3-97f389b613c9)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 5990
  Available CPU cores: 12
Binaries:
  Node: 20.17.0
  npm: 10.9.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Core, UI

**Comment by fuma-nama** [comment]
You probably missed the Next.js 15 blog post, make sure to update your code

**Comment by Gitstar-OC** [comment]
Sorry, will check it out.

**Comment by fuma-nama** [comment]
https://nextjs.org/blog/next-15
