### ISSUE TITLE
Modifying the ask AI  option

### ISSUE THREAD

**Issue by Gitstar-OC** [fuma-nama/fumadocs#1063]
### What problem will this feature address?

Currently the ask AI button does not get any attention or people does not know about it as it is in the bottom. ( I thought you removed this feature due to any problem but today I saw it) 

This feature will get some user attention toward the ask ai option to make users life simple instead of searching the complete docs. 

### Describe the solution you'd like

I am thinking of adding a border of opposite color to the option so that it will look better and get some attention, currently it is lost in the same colors as of the other things 

It looks like it's there in this screenshot. 
![image](https://github.com/user-attachments/assets/597ec1b2-4b07-4dbc-920e-7e7bb0caee5e)

But people miss them when you look in this screenshot
![image](https://github.com/user-attachments/assets/fac42d89-a223-4257-b88c-467036db7b65)

### Describe alternatives you've considered

I am also considering of an option that when I hover over the ask ai it will open up as the navigation bar component of the shadcn and maybe open a query box below or above or will directly. 

Or it should become a little bit bigger when someone hover over it. 

### Additional context

Adding a background or other color will make it more better for people to get and search what they are looking for instead of openening a new issue or query in the discussions.

**Comment by Gitstar-OC** [comment]
Also the current background color of the ( light theme) documentation looks **sick**!! Thinking of adding it in my docs too!

**Comment by fuma-nama** [comment]
we're working to add Inkeep, for now I prefer to make it less noticable
