### ISSUE TITLE
feat(CLI): Add a command to update fumadocs

### ISSUE THREAD

**Issue by SaadBazaz** [fuma-nama/fumadocs#1082]
### What problem will this feature address?

It'd be awesome to have a command like `pnpm fumadocs update` to update all relevant dependencies and components of fumadocs in one go. It's especially good for devs who haven't really messed around with the components and just want easy updates and compatibility.

### Describe the solution you'd like

 `update` command in fumadocs CLI.

### Describe alternatives you've considered

Manually updating the dependencies.

**Comment by fuma-nama** [comment]
do you mean to update installed components or simply the dependencies in `package.json`?
You can always use `pnpm update -i --latest` to update dependencies.

Updating install components isn't possible as each iteration of a minor release may introduce changes to existing components, and after modification it is no longer able to auto-update without losing your custom styles
