### ISSUE TITLE
Root selector does not update on group

### ISSUE THREAD

**Issue by mishushakov** [fuma-nama/fumadocs#1092]
### To Reproduce

I'm using the following structure:
<img width="291" alt="Screenshot 2024-11-22 at 15 00 43" src="https://github.com/user-attachments/assets/e4760e86-65df-4830-9bc3-10db1ceb6816">

I have (test) root and section root
repo: https://github.com/mishushakov/fuma-docs-repro

### Current vs. Expected behavior

The selector does not update when you switch roots if a root is group

<img width="393" alt="Screenshot 2024-11-22 at 15 00 19" src="https://github.com/user-attachments/assets/c06bf0b3-fa06-45a5-bece-2991ffa6dbcf">

<img width="386" alt="Screenshot 2024-11-22 at 15 00 25" src="https://github.com/user-attachments/assets/1d9da86f-deff-44a8-b792-20c71c766183">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Thanks for the reproduction. I found the problem, the tabs component accepts only url prop for items, which isn't enough to detect the correct group from pathname.

It's because group members will conflict with the other pages outside the group. (e.g. `/dir/(group)/page.md` and `/dir/another.md` yields urls with the same directory `dir`)

Going to make a fix tomorrow

**Comment by mishushakov** [comment]
Thank you so much!!

**Comment by fuma-nama** [comment]
Currently the check relies on object references, it should be working but welcome to reopen if the fix has problems
