### ISSUE TITLE
twoslash transformer leads to runtime error on the server

### ISSUE THREAD

**Issue by tylersayshi** [fuma-nama/fumadocs#1095]
### To Reproduce

Issue Reproduction: https://github.com/tylersayshi/fumadocs-twoslash-bug

### Current vs. Expected behavior

Bugs:

1. `// ^?` and other twoslash comments are not being transformed on the docs pages after adding the plugin following the docs: https://fumadocs.vercel.app/docs/ui/twoslash
2. Runtime error when attempting to use `twoslash` on the server in `components/code-block.tsx` for the home page

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:26 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8122
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.5.1
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.13.2
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Content Sources (e.g. Fumadocs MDX, Content Collections), Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

the project i am working on this for is here: https://github.com/tylersayshi/fuma-move

This work is to move arktype.io to fumadocs: https://github.com/arktypeio/arktype/issues/1111

**Comment by fuma-nama** [comment]
1. You need to enable it by adding `twoslash` meta string to codeblock.

2. It requires a Popup component to display the generated popups, you can import them from the package:

```ts
import { Popup, PopupContent, PopupTrigger } from 'fumadocs-twoslash/ui';
```

And pass it to components option.

I would suggest to provide the details of runtime error too if you have other questions, it helps me to locate the problem faster.

**Comment by fuma-nama** [comment]
Sorry for late, I've just made the Twoslash section docs up-to-date.

Hope it clarifies the problems: https://fumadocs.vercel.app/docs/ui/twoslash

**Comment by tylersayshi** [comment]
Thanks for the quick responses! 

Is the code for customizing the config file referring to the `next.config.js`?

```ts
import { defineConfig } from 'fumadocs-mdx/config';
import { transformerTwoslash } from 'fumadocs-twoslash';
import { rehypeCodeDefaultOptions } from 'fumadocs-core/mdx-plugins';
 
export default defineConfig({
  mdxOptions: {
    rehypeCodeOptions: {
      transformers: [
        ...(rehypeCodeDefaultOptions.transformers ?? []),
        transformerTwoslash(),
      ],
    },
  },
});
```

I am probably just configuring this wrong somehow.

**Comment by tylersayshi** [comment]
Oh it's the `source.config.ts` - sorry for my confusion there. #1 is now resolved for me and was not a bug at all. 🎉

re: the runtime error.

minimal reproduction: https://github.com/tylersayshi/fumadocs-twoslash-bug

<img width="861" alt="image" src="https://github.com/user-attachments/assets/6abc1e87-ba30-4e05-b106-ce0769758eab">

[link to related code block component](https://github.com/tylersayshi/fumadocs-twoslash-bug/blob/main/components/code-block.tsx)

This error I find confusion because it mentions that the error happens on the server where `path` should definitely be defined.

**Comment by tylersayshi** [comment]
I get the same error when doing this with

```ts
import { transformerTwoslash } from "@shikijs/twoslash";
```

So maybe this is upstream somehow?

**Comment by fuma-nama** [comment]
Hmm but it's indeed working on CodeSandbox, have you installed `@types/node`?

**Comment by fuma-nama** [comment]
took some time for me, it's a bundler issue because `typescript` has dynamic require of modules including `fs` and `path`.
You can add them to `serverExternalPackages`.


```ts
import * as Base from "fumadocs-ui/components/codeblock";
import { highlight } from "fumadocs-core/server";
import { transformerTwoslash } from "fumadocs-twoslash";
import { Popup, PopupContent, PopupTrigger } from "fumadocs-twoslash/ui";

export interface CodeBlockProps {
  code: string;
  wrapper?: Base.CodeBlockProps;
  lang: string;
}

export async function CodeBlock({
  code,
  lang,
  wrapper,
}: CodeBlockProps): Promise<React.ReactElement> {
  const rendered = await highlight(code, {
    lang,
    meta: {
      __raw: 'twoslash'
    },
    themes: {
      light: "github-light",
      dark: "vesper",
    },
    transformers: [transformerTwoslash()],
    components: {
      // @ts-expect-error -- JSX component
      pre: Base.Pre,
      Popup,
      PopupContent,
      PopupTrigger
    },
  });

  return <Base.CodeBlock {...wrapper}>{rendered}</Base.CodeBlock>;
}
```

```ts
import { createMDX } from "fumadocs-mdx/next";

const withMDX = createMDX();

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
    serverExternalPackages: ['twoslash', 'typescript'],
};

export default withMDX(config);
```

**Comment by tylersayshi** [comment]
wow! Thanks so much for the help! It all works super nicely now :)

**Comment by tylersayshi** [comment]
Oh wait one last question, it looks like the twoslash snippets are parsing strangely. Is the `meta.__raw: 'twoslash'` supposed to fix this?

<img width="626" alt="image" src="https://github.com/user-attachments/assets/a14d48c0-9709-4cca-8df5-090d3814ea6c">

**Comment by fuma-nama** [comment]
You probably forgot to add components option to JSX renderer, the `fumadocs-twoslash/ui` exported all required components.

**Comment by tylersayshi** [comment]
So the weird output above was because I was importing from `@shikijs/twoslash` for `transformerTwoslash` still by accident. 

I am now seeing this error 😅

```
Error: Language `js` not found, you may need to load it first
```

this issue seems relevant but maybe different? https://github.com/vuejs/vitepress/issues/4334

the popups are added here btw: https://github.com/tylersayshi/fuma-move/blob/main/components/code-snippets/Code.tsx#L27-L32

Maybe I need to mark another package as external? 
https://github.com/tylersayshi/fuma-move/blob/main/next.config.js#L8

**Comment by fuma-nama** [comment]
Yes it's relevant, codeblocks in popups may have a different language than the parent codeblock, but only the language of parent codeblock e.g. `ts` will be pre-loaded.

It's indeed a problem of Shiki, it doesn't support async markdown renderer so there's no official solution unless I make a PR to shiki.

for user-land workaround, you can pre-load all possible languages (ideally `bundledLanguages`) first.

```ts
import {
  getSingletonHighlighter,
  bundledLanguages
} from 'shiki';

await getSingletonHighlighter({
  langs: Object.keys(bundledLanguages)
})
```

**Comment by tylersayshi** [comment]
That worked great thanks!

I think this is my last related problem 🤞, but when I run `next build` the host output, shiki is not being run at all on the markdown snippet output.

you can see this deployed here: https://arkfuma.netlify.app/docs/properties

i've configured it as a static build and deploy (output: 'export'), but the same issue was present with the default next build & start.

**Comment by fuma-nama** [comment]
Not sure but it seems to be the problem of your `arktypeTextmate` in source configuration.

**Comment by tylersayshi** [comment]
oh! good find: fixed it here: https://github.com/tylersayshi/fuma-move/commit/a3e35a37c3654a2f550d217c82919a8d4faf0195

**Comment by giftedl** [comment]
> Yes it's relevant, codeblocks in popups may have a different language than the parent codeblock, but only the language of parent codeblock e.g. `ts` will be pre-loaded.
> 
> It's indeed a problem of Shiki, it doesn't support async markdown renderer so there's no official solution unless I make a PR to shiki.
> 
> for user-land workaround, you can pre-load all possible languages first (ideally `bundledLanguages`).
> 
> import {
>   getSingletonHighlighter,
>   bundledLanguages
> } from 'shiki';
> 
> // before highlight call
> await getSingletonHighlighter({
>   langs: Object.keys(bundledLanguages)
> })
> Or you can just drop the `highlight` function and [go with Shiki + your custom config](https://fumadocs-dev.vercel.app/docs/ui/twoslash#using-on-runtime), so you can have full control on this.

@fuma-nama Where is this `highlight` function? Your links are broken.

**Comment by fuma-nama** [comment]
I guess you want to use the `highlight` function? See https://fumadocs.dev/docs/ui/components/dynamic-codeblock#server-component

**Comment by giftedl** [comment]
> I guess you want to use the `highlight` function? See [fumadocs.dev/docs/ui/components/dynamic-codeblock#server-component](https://fumadocs.dev/docs/ui/components/dynamic-codeblock#server-component)

Thanks. That's what I was looking for. I was trying to use Twoslash but it wasn't working for the exact same error because the Node.js `EventEmitter.on` API had two JS functions in its JSDoc declaration.

**Comment by fuma-nama** [comment]
even without that, in `source.config.ts`, you can specify the `langs` option with `mdxOptions.rehypeCodeOptions.langs` in `defineConfig()`

**Comment by giftedl** [comment]
Oh, okay. Thanks again.
