### ISSUE TITLE
Built-in search in mandarin config throw error

### ISSUE THREAD

**Issue by riccox** [fuma-nama/fumadocs#1102]
### To Reproduce

1. use latest auto start template to create a docs project.
2. config mandarin search by this [steps](https://fumadocs.vercel.app/docs/headless/search/orama#special-languages) in docs.
3. start dev server
4. enter some words input search input.
5. see dev server output.

### Current vs. Expected behavior

throw orama tokenizer type error, and without any search results.

```
node_modules/fumadocs-core/node_modules/@orama/orama/dist/esm/components/index.js (130:1) @ eval
TypeError: tokens is not iterable
    at eval (./app/api/search/route.ts:17:94)
  128 |                 const tokens = tokenizer.tokenize(value, language, prop, false);
  129 |                 implementation.insertDocumentScoreParameters(index, prop, internalId, tokens, docsCount);
> 130 |                 for (const token of tokens) {
      | ^
  131 |                     implementation.insertTokenScoreParameters(index, prop, internalId, tokens, token);
  132 |                     node.insert(token, internalId);
  133 |                 }
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
I found that it's a upstream problem caused by invoking `tokenizer.tokenize` without `await`, they made `insert` methods sync but it's not compatible with `tokenizer`, will report it to Orama later.

**Comment by riccox** [comment]
any updates?

**Comment by fuma-nama** [comment]
Orama team responded but no updates from them so far, I think we can only downgrade to older Orama versions to fix the bug.

Otherwise, it may only work using English tokenizer, but that means a Chinese query will have no results.

**Comment by fuma-nama** [comment]
Downgraded on the latest release, it should be working fine now

**Comment by riccox** [comment]
Better to hear that fixed.

**Comment by rjjan** [comment]
Hi Riccox and Fuma, @riccox @fuma-nama 

I have similar issue but my issue is I can't get the search result.
Do I need to config any i18n in the Fumadocs project ?

1. yarn create fumadocs-app
2. use config mandarin search by this [steps](https://fumadocs.vercel.app/docs/headless/search/orama#special-languages) in docs.
3. yarn dev
4. no error message in the console, however no search result either.

Did i miss any configuration to enable the chinese search function ?

Thanks.

**Comment by zjy365** [comment]
> Hi Riccox and Fuma, @riccox @fuma-nama
> 
> I have similar issue but my issue is I can't get the search result. Do I need to config any i18n in the Fumadocs project ?
> 
> 1. yarn create fumadocs-app
> 2. use config mandarin search by this [steps](https://fumadocs.vercel.app/docs/headless/search/orama#special-languages) in docs.
> 3. yarn dev
> 4. no error message in the console, however no search result either.
> 
> Did i miss any configuration to enable the chinese search function ?
> 
> Thanks.

The original issue was "TypeError: tokens is not iterable". After updating Fumadocs and downgrading @orama/orama, the same issue occurred with the following versions: 
- "@orama/orama": "2.1.1",
- "@orama/stopwords": "2.1.1",
- "@orama/tokenizers": "2.1.1",
- "fumadocs-core": "14.6.8",
- "fumadocs-mdx": "^11.2.2",
- "fumadocs-ui": "14.7.0".

**Comment by fuma-nama** [comment]
You probably have not re-installed the node modules, and Orama v3 was accidentally picked by Next.js. Try delete `node_modules` and install it again with `pnpm i`

Also make sure to use the same versions for both core & ui package, the latest is 14.7.0
