### ISSUE TITLE
Adding 2 seperate layouts options for the documentation site. 

### ISSUE THREAD

**Issue by Gitstar-OC** [fuma-nama/fumadocs#1103]
### What problem will this feature address?

Well I and most other people like the navbar on the documentation page that is at thet top rather than all the links in the sidebar. 

### Describe the solution you'd like

I am working on a navbar feature that will do the same things for the links and search that is on the sidebar. The people will get the option to select which option they would like to use for their documentation site. Option would be all the links in the sidebar like the current docs has or all the links and some things in the navbar.  I have implemented a version of this on my website https://mindect.vercel.app. Where the navbar that I have used on the homepage and /learn page could also be used with the documentation page leaving the documentaton with just the preffered link. 

### Describe alternatives you've considered

N/A

### Additional context

I think people will use fumadocs more often as they prefer horizontal navbar. I have seen some very recent documentation site which are using Mitlify which I think is also built on top of Nextra and charges people for that. This documentaton framework is awesome and I am happy to contribute to it.

**Comment by fuma-nama** [comment]
Already implemented, see https://fumadocs.vercel.app/docs/ui/blocks/layout#notebook

**Comment by Gitstar-OC** [comment]
Oh, that is great!! I did not know it was there and was thinking to do it again :) Tell me if you have any other features for in the future. 👍

**Comment by Gitstar-OC** [comment]
Maybe like this 
![image](https://github.com/user-attachments/assets/e572481e-66ea-47fe-afe2-79ef0ddaeb57)


But better, I am experimenting with various things do you have any ideas or features that I can implement.

**Comment by fuma-nama** [comment]
maybe go with `fumadocs add` and add all layouts to your project, this way you will have full ability to customise it
