### ISSUE TITLE
Add support for serializing HTML tags (web components) in simple Markdown (.md) files (e.g. remark-html plugin)

### ISSUE THREAD

**Issue by kaesar** [fuma-nama/fumadocs#1106]
### What problem will this feature address?

I want to use Fumadocs with some simple Markdown (.md) files that includes native web components (instead of MDX) and I use to use rendering it with `markdown-it` parser (and including a tag script in some layout) in another technology, but...

> When I try to use `html` tags with Fumadocs (in `.md` files) this components are Not rendering any more.

### Describe the solution you'd like

Just the capacity or posibility to use `html` tags with simple Markdown (.md) files similar with `markdown-it` (e.g. remark-html plugin)

### Describe alternatives you've considered

Migrate my `.md` files to MDX and migrate native web components (made with Lit) but it sounds crazy and I want to adopt Fumadocs (now that I know Fumadocs I love it)

### Additional context

Project with web components: <https://github.com/kaesar/onmind-cui>

**Comment by fuma-nama** [comment]
I'm not planning to add Web Components support, you should use it with JSX or a React component wrapping a web component, or see https://react.dev/reference/react-dom/components#custom-html-elements
