### ISSUE TITLE
Feature Request: Seperate UI for Blogs. 

### ISSUE THREAD

**Issue by amripandey** [fuma-nama/fumadocs#1113]
### What problem will this feature address?

I am a fan of writing and reading technical blogs and want to manage my own blogs.
Right now i am writing every thing under the docs UI . 

So I request for feature for blogs section also

### Describe the solution you'd like

I really like the blogs UI of nextra. We can get inspiration from it. 
Further we can also add the comment and like options

### Describe alternatives you've considered

I currently don't know 
But i am a big fan of fumadocs and want it to be a problem solver and easy as it is always been.

**Comment by fuma-nama** [comment]
Currently I want fumadocs to focus on purely docs features, blog UI won't be considered.

You can make the blog UI easily without Fumadocs UI, like using your custom layout with Shadcn UI or build with v0.dev. Blog is relatively simple so it isn't too necessary to have it builtin. 

Fumadocs UI has typography styles that you can use via `prose` class, and Fumadocs MDX offered the tool to manage blog content. I also preferred the flexibility this way.

**Comment by fuma-nama** [comment]
And for comment areas, try https://utteranc.es, or I personally made a package called fuma-comment for my blog, but it requires self hosting the database, probably too heavy for simple use cases.

**Comment by fuma-nama** [comment]
I think in a form of guide would be better
Welcome to share your thoughts: https://fumadocs-dev.vercel.app/blog/make-a-blog
