### ISSUE TITLE
Potential Regression in nav dropdown

### ISSUE THREAD

**Issue by chronark** [fuma-nama/fumadocs#1120]
### To Reproduce

 Upgrading from "fumadocs-ui": "14.4.0" to "fumadocs-ui": "14.5.4", I noticed that the nav dropdown stops working
 
I rolled back to the previous version and can confirm it works, so I doubt it's something I did.

1. git clone git@github.com:unkeyed/unkey.git
2. cd unkey/apps/engineering
3. pnpm install
4. pnpm dev
5. open http://localhost:3000/docs/contributing
6. see the nav dropdown

### Current vs. Expected behavior

It should display correctly, but doesn't.

You can still click on it, but it looks empty by default 
![CleanShot 2024-11-27 at 10 29 49@2x](https://github.com/user-attachments/assets/e19db371-e2f3-46eb-bb6d-62ba70ce40ec)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.6.9
Relevant Packages:
  next: 14.2.10 // An outdated version detected (latest is 15.0.3), upgrade is highly recommended!
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Feels weird, it's indeed working for me. Have to try on CodeSandbox later

![image](https://github.com/user-attachments/assets/5e122122-54d3-467f-9afc-4a8d03481091)
![image](https://github.com/user-attachments/assets/b6428fba-c544-4b46-810e-619baefd8b40)

**Comment by fuma-nama** [comment]
Sorry I cannot reproduce the issue locally or on CodeSandbox.
The trigger is empty only when no item selected (e.g. no items matching the current pathname), and the last matching item will be the selected item.

**Comment by mishushakov** [comment]
I'm having the same now :-(

**Comment by fuma-nama** [comment]
Need a minimal reproduction for this one

**Comment by fuma-nama** [comment]
tried to fix it by changing the way to match items, since I cannot reproduce the issue, I might need your help to test if the fix works.
