### ISSUE TITLE
AutoTypeTable path should relative to mdx file rather than next docs app running directory

### ISSUE THREAD

**Issue by hxlhxl** [fuma-nama/fumadocs#1121]
### What problem will this feature address?

If the content directory locate in another directory that is irrelevant with next app project.say config like this

```js
export const { docs, meta } = defineDocs({
  // dir: 'src/content/docs',
  dir: '../../../docs',
})
```

and if  mdx doc inside `../../../docs` want to use `AutoTypeTable` like this

```tsx
<AutoTypeTable path="./props.ts" name="TOCItemType" />
```

then "no such file or directory" error occurred because this path is relative to next app running directory

### Describe the solution you'd like

I dig into the typescript source code but can't find a suitable solution,what if AutoTypeTable could access the `vfile.cwd` then it's easy to achieve that

### Describe alternatives you've considered

```tsx
<AutoTypeTable path="../../../docs/..../.../props.ts" name="TOCItemType" />
```

apparently it's not acceptable because the mdx have noting to do with next app running directory.

**Comment by fuma-nama** [comment]
It's simply impossible to access the original invoker's file name from a React component, and `AutoTypeTable` included.
You can only workaround it with
```js
import * as path from "node:path"

export const dir = path.dirname(fileURLToPath(import.meta.url))
```

and pass path as `path.join(dir, "./relative")`

**Comment by hxlhxl** [comment]
well thank u for providing a working solution.
