### ISSUE TITLE
Why it shows missing root provider while I still have all of the things 

### ISSUE THREAD

**Issue by Gitstar-OC** [fuma-nama/fumadocs#1134]
### To Reproduce

Run the following commands

```bash 
git clone https://github.com/Gitstar-OC/pear-landing-page
cd pear-landing-page
pnpm install 
pnpm run dev
```

and then head to http://localhost:3000/docs it will show an error. 

### Current vs. Expected behavior

It should show the docs properly but it is not doing that. 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 5990
  Available CPU cores: 12
Binaries:
  Node: 20.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // An outdated version detected (latest is 15.0.3), upgrade is highly recommended!
  eslint-config-next: 14.2.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core, UI

**Comment by fuma-nama** [comment]
Please provide a minimal reproduction instead, and make sure to add Root Provider to tour root layout.
