### ISSUE TITLE
 ✘ [ERROR] Could not resolve "/app/source.config.ts"

### ISSUE THREAD

**Issue by Manmit124** [fuma-nama/fumadocs#1153]
### To Reproduce

![Screenshot 2024-12-12 164925](https://github.com/user-attachments/assets/dadc01d4-ba63-40b7-84e9-d6bc822bd2a1)

### Current vs. Expected behavior

I am encountering the following error during the Docker build process, even though I have correctly set up source.config.ts

### Provide environment information

```bash
"fumadocs-core": "^14.4.0",
    "fumadocs-mdx": "11.1.1",
    "fumadocs-openapi": "^5.7.4",
    "fumadocs-typescript": "^3.0.2",
    "fumadocs-ui": "14.4.0",
    "lucide-react": "^0.460.0",
    "next": "15.0.3",
    "path": "^0.12.7",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "rimraf": "^6.0.1",
    "shiki": "^1.23.1",
    "stream": "^0.0.3",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@fumadocs/cli": "^0.0.3",
    "@types/mdx": "^2.0.13",
    "@types/node": "22.9.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "autoprefixer": "^10.4.20",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "postcss": "^8.4.48",
    "tailwindcss": "^3.4.14",
    "tsx": "^4.19.2",
    "typescript": "^5.6.3"
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
`fumadocs-mdx` resolves the `source.config.ts` from cwd, you are likely running the command in a directory that doesn't contain `source.config.ts`

**Comment by Manmit124** [comment]
![image](https://github.com/user-attachments/assets/7443f2f3-9652-4472-a868-d4fd52409e62)
here is the screenshort

**Comment by fuma-nama** [comment]
Does it happen only with Docker or `next build` too? It could be a problem of your Dockerfile, I need your full config or a reproduction (ideally a github repo)

**Comment by Manmit124** [comment]
![image](https://github.com/user-attachments/assets/ac6c6647-0435-418f-acba-06de659a302b)
it's also happened with next build, but it shows a different error

**Comment by Manmit124** [comment]
> Does it happen only with Docker or `next build` too? It could be a problem of your Dockerfile, I need your full config or a reproduction (ideally a github repo)

Sorry, I can’t give you access as it’s my company’s project, so it’s private.

**Comment by fuma-nama** [comment]
You can create a minimal reproduction that doesn't contain any private code, regarding your screenshot I think you have installed a version of `lucide-react` that is too old to work with Fumadocs UI

**Comment by Manmit124** [comment]
Installing the latest version of `lucide-react` resolved the error, but the Docker build error is still persisting.

**Comment by Manmit124** [comment]
Let me know if we can connect to resolve this issue.

**Comment by fuma-nama** [comment]
I need some information about your Dockerfile to investigate the issue

**Comment by Manmit124** [comment]
```
FROM node:20.10-alpine3.18

WORKDIR /app

COPY package*.json ./

RUN npm install --verbose

COPY . .

RUN npx next telemetry disable

CMD ["npm", "run", "dev"]
EXPOSE 3000

```
 Dockerfile

**Comment by fuma-nama** [comment]
Hmm why do you run `npm install` before copying all files to workdir? It means during the install, `source.config.ts` is not being copied hence resulting in an error

**Comment by fuma-nama** [comment]
Cannot reproduce the problem, make sure to upgrade dependencies to latest versions, you may use `next build` as a better way to test build problems.

**Comment by shakedhagag** [comment]
I also had this issue, building with pnpm build (next build) worked fine but docker build wasn't.
After seeing this issue I figured I was not including this file in the docker build dir.
btw I was using the default suggested nextjs dockerfile, so I think it will be good to include this in the docs. 
I can add that to the Manual Configuration section, @fuma-nama wdyt?

**Comment by fuma-nama** [comment]
PR welcome ;)
