### ISSUE TITLE
Module not found: Can't resolve 'ajv/dist/core'

### ISSUE THREAD

**Issue by ronal2do** [fuma-nama/fumadocs#1156]
### To Reproduce

I've a monorepo, after upgrading to 14.6.0, and fumadocs-openapi to 5.8.2
I'm no longer able to build 
looks the issue is more on the @scalar/openapi-parser package than on yours, but just to register

### Current vs. Expected behavior

After downgrading to 

```json
    "fumadocs-core": "14.5.4",
    "fumadocs-docgen": "^1.3.2",
    "fumadocs-mdx": "11.1.2",
    "fumadocs-openapi": "^5.7.5",
    "fumadocs-twoslash": "^2.0.1",
    "fumadocs-ui": "14.5.4",
```
everything works as expected

### Provide environment information

```json
    "fumadocs-core": "14.6.0",
    "fumadocs-docgen": "^1.3.2",
    "fumadocs-mdx": "11.1.2",
    "fumadocs-openapi": "^5.8.2",
    "fumadocs-twoslash": "^2.0.2",
    "fumadocs-ui": "14.6.0",
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

@rkt/web:build: ../../node_modules/ajv-draft-04/dist/vocabulary/draft4.js
@rkt/web:build: ../../node_modules/ajv-draft-04/dist/index.js
@rkt/web:build: ../../node_modules/@scalar/openapi-parser/dist/lib/Validator/Validator.js
@rkt/web:build: ../../node_modules/@scalar/openapi-parser/dist/index.js
@rkt/web:build: ../../node_modules/fumadocs-openapi/dist/server/index.js
@rkt/web:build: ./app/source.ts
@rkt/web:build: ./app/(llms)/llms.txt/route.tsx
@rkt/web:build: 
@rkt/web:build: ../../node_modules/ajv-draft-04/dist/vocabulary/draft4.js
@rkt/web:build: Module not found: Can't resolve 'ajv/dist/vocabularies/applicator'

**Comment by fuma-nama** [comment]
You can install `ajv-draft-04` to the project, that can probably fix the issue

**Comment by fuma-nama** [comment]
I think I can work on another PR next month, for now I will add the dependency to Fumadocs itself as a temporary fix
