### ISSUE TITLE
Inconsistent icon size on the sidebar

### ISSUE THREAD

**Issue by leonho** [fuma-nama/fumadocs#1160]
### To Reproduce

If the document title is longer, the icon will shrink.

Screenshot:
![CleanShot 2024-12-13 at 17 06 40](https://github.com/user-attachments/assets/d1e03a56-ec8e-4be2-ba60-34f6c9e2f279)

### Current vs. Expected behavior

icon size should stay the same

### Provide environment information

```bash
Fumadocs v12.1
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
You need to add `flex-shrink: 0`
