### ISSUE TITLE
Missing typesVersions in 14.6.1

### ISSUE THREAD

**Issue by sudoaugustin** [fuma-nama/fumadocs#1162]
### To Reproduce

# 1. Install Package
`pnpm add fumadocs-ui@latest`

# 2. Import components
```tsx
import { Card, Cards } from "fumadocs-ui/components/card";
```

### Current vs. Expected behavior

Current behavior
<img width="934" alt="Screenshot 2024-12-14 at 9 45 40 PM" src="https://github.com/user-attachments/assets/612079d3-cb12-4e32-b9b0-c27948bd5fde" />
 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.8.3
  Yarn: 4.0.2
  pnpm: 9.14.4
Relevant Packages:
  next: 15.0.3 // There is a newer version (15.1.0) available, upgrade recommended!
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
Next.js Config:
  output: N/A
 ⚠ There is a newer version (15.1.0) available, upgrade recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

UI

### Additional context

The root cause is that you removed typesVersions from package.json in version 14. I hope adding it back will solve this issue. Recently faced the same thing in my package.

Thank you very much for making this lib.

**Comment by fuma-nama** [comment]
This is expected, please set module resolution to bundler to your tsconfig
