### ISSUE TITLE
Exclude mdx source files based on frontmatter settings

### ISSUE THREAD

**Issue by hxlhxl** [fuma-nama/fumadocs#1165]
### What problem will this feature address?

control the output by doc content itself.

```mdx
---
title: hello
public: true
---
```

if `public` field is `true` then generate into `.source/source.config.mjs` else not

### Describe the solution you'd like

append a filter logic to  `packages/mdx/src/map/generate.ts::generateJS` after `getCollectionFiles` call.

### Describe alternatives you've considered

None

**Comment by fuma-nama** [comment]
Fumadocs MDX still needs to read the file to parse frontmatter. I think it would be better to use filter on the collection entries in `lib/source.ts`, this won't introduce new concepts and gets more flexibility like allowing usage with `draftMode`.

**Comment by hxlhxl** [comment]
Yes, but it seems like this will make a big change to `packages/core/src/source/loader.ts::createOutput` and I'm not sure that I can make it possible.
and, is this a valid feature? Can I try to make a pr later?

**Comment by fuma-nama** [comment]
I mean: 

```ts
import { docs, meta } from '@/.source';
import { createMDXSource } from 'fumadocs-mdx';
import { loader } from 'fumadocs-core/source';
 
export const source = loader({
  baseUrl: '/docs',
  source: createMDXSource(docs.filter(...), meta),
});

```

**Comment by hxlhxl** [comment]
OK, it works

```ts
createMDXSource(docs.filter(doc => {
    if (doc._exports.frontmatter.public === true) {
      return true;
    }
    return false;
  }), meta)
```

thanks for your time.
