### ISSUE TITLE
pass mdx components props to imported mdx automatically

### ISSUE THREAD

**Issue by hxlhxl** [fuma-nama/fumadocs#1172]
### What problem will this feature address?

if we include another mdx file, the overwrited components like `pre` we define will not take effect.

````mdx
---
title: hello
public: false
---

hello world

```typescript
console.log('hello world')
```

import A from './a.mdx'
<A />

````

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

I must provide components manually this way. it's kind of awkward

```typescript
<A components={props.components} />
```

**Comment by fuma-nama** [comment]
I think it's great to have this, having less control over the original MDX compiler is great & `A` is essentially a React component, I want to avoid changes to the AST
