### ISSUE TITLE
Ability to custom the sidebar items with JSX

### ISSUE THREAD

**Issue by oscartbeaumont** [fuma-nama/fumadocs#1176]
### What problem will this feature address?

It would be really nice to be able to replace a sidebar navigation item with custom JSX. This would make the sidebar way more flexible.

I understand you can create a fully custom sidebar layout but it would be nice if that was avoidable to make maintaining the site easier over time.

My specific goal to to make a sidebar item that looks like the following:
<img width="254" alt="Screenshot 2024-12-19 at 10 19 48 pm" src="https://github.com/user-attachments/assets/8e65c7f5-7dc3-4417-8863-284897f8f3f9" />

Current I can not work out a way to do it (screenshot was created through inspect element).

My idea is that clicking anywhere but the logo will open a specific page in my documentation but by clicking the logo you can quickly jump to the external package registry. This saves the user having to click into the page and then clicking another link to get to the external page's page.

One thing to note is that given `a` tags can't be nested I would need complete control over rendering the sidebar element to implement this.

### Describe the solution you'd like

It would be cool to have something like:
```
export const baseOptions: BaseLayoutProps = {
  sidebar: {
    itemComponent: (item: NavbarItemProperties) => <a ...>...</a>,
  }
};
```

The default implementation would match the the current element's code but the user could take full control over the JSX element if they desired. We would parse in `item` so that the user was able to match on specific navbar items to customise. I suspect returning `undefined` from this function would cause the default to render. This would allow the user to match on only specific items to modify and return `undefined` for the rest of them. `null` would be an empty item.

### Describe alternatives you've considered

I tried using the `pageTree.attachFile` argument to `loader` but the node returned from it is injected inside the `a` tag which would be a problem for my usecase as it would mean the npm icons `a` tag would be inside the menu item's  `a` tag which is not allowed.

**Comment by oscartbeaumont** [comment]
That is perfect. Can't believe I missed it.

Thank you for such an awesome project and the quick response!

**Comment by rogerluan** [comment]
Hey @fuma-nama or @oscartbeaumont - where is this `sidebar.components` prop being used (or supposed to be found)? I searched everywhere in the official docs and couldn't find that anywhere 😅 

The desired behavior I want is to be able to declare an external link in my `pagas` array in `meta.json` like `"[Megaphone][Product Updates](https://changelog.statused.com/)",` and have it automatically include a small icon indicating the link opens in a new tab (external link). I know that I can have this in the regular icon placement if I remove my custom icon, but I'd like to have both 🤕

If I can find that sidebar.components I'll customize this behavior myself - but it'd be great if it allowed for this out-of-the-box as I think it's a common use case :)

Thanks in advance!

**Comment by fuma-nama** [comment]
You can find it in DocsLayout
