### ISSUE TITLE
Remove ESM requirement from `fumadocs-mdx/next` to enable using `next.config.ts`.

### ISSUE THREAD

**Issue by lacymorrow** [fuma-nama/fumadocs#1178]
### What problem will this feature address?

I'd like to use TypeScript for my next config.

### Describe the solution you'd like

Remove the requirement for next config to be an esm module.

### Describe alternatives you've considered

using mjs or js files is fine but shouldn't be necessary

**Comment by fuma-nama** [comment]
I will wait for Next.js team to fix existing ESM compatibility, it's their upstream issue and this will only hide that problem. Fumadocs will remain ESM only
