### ISSUE TITLE
Locale Not Being Preserved with `next/link` in Next.js

### ISSUE THREAD

**Issue by jorgedanisc** [fuma-nama/fumadocs#1182]
### To Reproduce

1. Follow the manual installation for i18n via the fumadocs docs
2. Use `next/link` to navigate between pages:
   ```jsx
   import Link from 'next/link';

   <Link href="/about">
     Go to About Page
   </Link>
   ```
3. Start the app and switch to a non-default locale (e.g., `/fr`).
4. Click the link to navigate to the `/about` page.

#### Expected Behavior
The locale should be preserved (e.g., navigating to `/fr/about`).

#### Actual Behavior
The locale is not preserved, and the app navigates to the default locale’s route (e.g., `/about`).

### Provide environment information

```bash
Next.js Version: 15.2
Fumadocs Version: 
    "fumadocs-core": "14.6.1",
    "fumadocs-mdx": "11.1.2",
    "fumadocs-ui": "14.6.1",
Node.js Version: 20
Operating System: MacOS 15.2
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

When using `next/link` in a Next.js project with `i18n` enabled, the locale is not being preserved automatically when navigating between pages. This occurs despite having the `i18n` configuration properly set up in `next.config.js`.

**Comment by fuma-nama** [comment]
This is expected, you need to configure that manually by making your own Link component. Fumadocs is not a i18n library

**Comment by fuma-nama** [comment]
Making a better guide, see
https://fumadocs-dev.vercel.app/docs/ui/internationalization#navigation

**Comment by jorgedanisc** [comment]
Great, looking forward to test it out ! 

I see that fumadocs isn't an i18n lib, but I actually see it as a big whole Nextjs "Layout" that enables docs and mdx pages. I have been using it and looks promising, great work.
