### ISSUE TITLE
Enabling custom shortcuts to Navigate to certain documents, like we use for Search

### ISSUE THREAD

**Issue by KabinManandhar** [fuma-nama/fumadocs#1186]
### What problem will this feature address?

It would be much convenient to have shortcuts assignable to each document making it much easier to navigate like we quickly access search bar. 

### Describe the solution you'd like

Simple short cuts like NumKey 1 for Getting started, NumKey 2 for Manual Installation and more custom key to assign.

### Describe alternatives you've considered

Probably could have added shortcuts myself as it's not impossible to do, but having it baked into fumadocs itself would be a great experience for other's as well.
It's a simple feature request which you already have implemented for search, just expecting it for other pages as well.

**Comment by fuma-nama** [comment]
Why don't use `useRouter` + `useEffect` for this
