### ISSUE TITLE
Create Next Docs App failed with Contentlayer

### ISSUE THREAD

**Issue by CMAULTOP** [fuma-nama/fumadocs#148]
nothing was fixed, everything worked for me through pnpx. Only this works in rpm:
(where the check mark works)
- [ ] Default (Contentlayer)
- [ ] Advanced (Contentlayer)
- [x] Default (Next Docs MDX)

Error when Default:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gug@0.0.0
npm ERR! Found: next@14.0.1
npm ERR! node_modules/next
npm ERR!   next@"14.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"0.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/codespace/.npm/_logs/2023-11-02T10_16_18_972Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-11-02T10_16_18_972Z-debug-0.log
Install failed
```

Advanced:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gdfg\@0.0.0
npm ERR! Found: next@14.0.1
npm ERR! node_modules/next
npm ERR!   next@"14.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"0.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/codespace/.npm/_logs/2023-11-02T10_17_58_568Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-11-02T10_17_58_568Z-debug-0.log
Install failed
```

Again, I will say that I tested on github codespaces and I think that there are updated versions and working.

**Comment by fuma-nama** [comment]
Contentlayer doesn't support Next.js 14 in their peer dependency yet, you have to disable peer deps error and try again. Pnpm won't throw an error for missing peer deps issue, you can use it as a workaround.

**Comment by fuma-nama** [comment]
Please use Next Docs one if you don't need Contentlayer specific functionality

**Comment by birchwork** [comment]
Modify node_modules/next-contentlayer/package.json,  next@"^12 || ^13 || ^14

**Comment by fuma-nama** [comment]
Surprisingly this PR hasn't been merged: contentlayerdev/contentlayer#576

**Comment by xXQiuChenXx** [comment]
Just add `--legacy-peer-deps` in your command, and itshould work well.
Example: `npm install --legacy-peer-deps`

**Comment by fuma-nama** [comment]
According to the state of Contentlayer: https://github.com/contentlayerdev/contentlayer/issues/429, I'll recommend Fumadocs MDX if you don't need any Contentlayer-only features.

**Comment by fuma-nama** [comment]
Will close this as Next.js 15 RC has been released, we will focus on Fumadocs MDX until Contentlayer has resumed maintenance.
