### ISSUE TITLE
[Feature Request] Add an external link to sidebar

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#264]
### Discussed in https://github.com/fuma-nama/fumadocs/discussions/261

<div type='discussions-op-text'>

<sup>Originally posted by **anthonyshew** February 20, 2024</sup>
Currently rewriting the Turborepo documentation using Fumadocs and it's incredible.

I have a small feature request for being able to add an external link to the sidebar similar to [the Nextra API](https://nextra.site/docs/docs-theme/page-configuration#external-links).

It's also possible that I could build this functionality using the primitives in fumadocs but couldn't figure it out. Is there a simple, idiomatic way that I haven't yet discovered?

Thank you again for the great work!</div>

@fuma-nama replied there but asked that I open an Issue for my feature request. Responding here:
> I prefer adding a sidebar footer or nav link instead tho

We're sensitive to the exact placement of these links given the information architecture we're trying to create. Adding these links in a sidebar footer is closer to what we need. However, that pushes these links to the bottom of the sidebar when we need them in between other items within the sidebar.

> However, if you can manipulate the page tree directly, you can insert a Item node.

I thought about doing this but wanted to make sure there wasn't a more first-party way of adding an external link before I went for it. Additionally, reading the documentation, I couldn't quite figure out the best way go about it.

**Comment by fuma-nama** [comment]
With the page tree API:

```ts
tree.children.push({ type: 'page', name: 'Name', url: 'https://google.com', external: true })
```

Most integrations, including Fumadocs MDX, don't support external links in `meta.json`. You'll have to manipulate the page tree directly. I'm thinking of a better syntax for `meta.json` so that you can add external links in the `pages` property while it is straightforword

**Comment by anthonyshew** [comment]
I've now written this out and it (almost!) works how I'd hope:
```js
export const { getPage, getPages, pageTree } = loader({
  baseUrl: "/repo/docs",
  rootDir: "repo-docs",
  source: createMDXSource(map, {
    schema: { frontmatter: docFrontmatterSchema },
  }),
});

// Insert external links into the page tree
pageTree.children.splice(9, 0, { type: 'page', name: 'Glossary', url: 'https://vercel.com/docs/vercel-platform/glossary', external: true })
pageTree.children.splice(10, 0, { type: 'page', name: 'Changelog', url: 'https://github.com/vercel/turbo/releases', external: true })

export const pageTreeWithExternals = pageTree
```

Almost works - but a couple drawbacks:
- I'm having to splice in at a specified index which is fairly brittle. If I ever need to change our sidebar, I'd worry that these links might end up in a different position than I had originally meant.
- Pictured below, the neighbor link becomes a pointer to the external link which feels unintended. I could rebuild the footer with the original `pageTree` but would love for `fumadocs` to handle it for me. 😄 
   - Of course, that may be at odds with your vision for how "batteries included" you envision `fumadocs` should be. Your API design intent leans heavily into "less magic, more composability", which I respect.

![CleanShot 2024-03-02 at 22 00 00](https://github.com/fuma-nama/fumadocs/assets/35677084/25beb46a-1207-4a94-8bb5-7ab7ec885672)


---
As far as an API suggestion would go, [the Nextra API](https://nextra.site/docs/docs-theme/page-configuration#external-links) has worked well for me in the past. Personally, I'd probably rename `href` to `externalHref` and always open the link in a new window by default - but would still be happy with your take on the API!

The one gap that I do see is handling the icon for these external links since this API is in the JSON definitions. I don't think I have any great suggestions for how that would work at the moment.

**Comment by fuma-nama** [comment]
That makes sense. I'm working to add a new syntax to `meta.json` so that you can seamlessly add an external link, like `[Text](https://google.com)` similar to markdown. 

Regarding to your first point, you may locate the item with `.find` but the ideal approach would still be integrating it as a built-in feature.

**Comment by fuma-nama** [comment]
Also you might want to have a look at the [icon](https://fumadocs.vercel.app/docs/headless/source-api#icons) option for handling icons.

**Comment by anthonyshew** [comment]
Oh, getting to use Markdown there would be quite clever!

I had thought about using `.find` but still am thinking it would be brittle, depending on what I filter for in the callback. Whatever content I use to find the node is subject to change and it's likely that I'd still want to maintain the order I intended despite those content changes.

That icon API looks useful! Will see what I can do with that.

**Comment by fuma-nama** [comment]
Supported in 10.0.0

**Comment by anthonyshew** [comment]
Works like a charm! Thank you again!

**Comment by MorelSerge** [comment]
I can link internal documentation pages too, but the sidebar content remains the same, even if you navigate to a entire separate root (the root toggle does change).

Is this by design? I'm on the latest version, and checked the docs, but couldn't find a way to also update the sidebar upon navigating to an internal link.

**Comment by fuma-nama** [comment]
Need more details on your problem, please open a separate issue with more info attached
