### ISSUE TITLE
[Feature Request] Only open specific sidebar sections by default

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#265]
### Discussed in https://github.com/fuma-nama/fumadocs/discussions/262

<div type='discussions-op-text'>

<sup>Originally posted by **anthonyshew** February 20, 2024</sup>
Another feature request!

I'd like to be able to have only certain sections of the sidebar open by default, as shown in this screenshot.

![CleanShot 2024-02-20 at 23 13 00](https://github.com/fuma-nama/fumadocs/assets/35677084/889f568b-b493-4b5a-87c8-610553bd9caf)

I'm using `defaultOpenLevel: 0` to keep everything closed at the start - but would love to have the first two sections open when users first visit the docs.

Is this possible?</div>

Sorry again for opening Discussions!

**Comment by fuma-nama** [comment]
Will be supported in 9.1.0

**Comment by anthonyshew** [comment]
Awesome! Thanks!

**Comment by anthonyshew** [comment]
Just tried it out.

Perfect! Thank you again!
