### ISSUE TITLE
[bug] having issues hiding table of contents (`toc`)

### ISSUE THREAD

**Issue by ryanwaits** [fuma-nama/fumadocs#268]
**Describe the bug**
im trying to hide the `toc` with `toc: false` according to the docs, but im unable to get this to work 

**here are the versions im on**
```bash
"fumadocs-core": "9.1.0",
"fumadocs-mdx": "8.1.0",
"fumadocs-openapi": "^1.1.0",
"fumadocs-ui": "9.1.0"
```

**Expected behavior**
1. Create an `.mdx` file inside `content/docs`
2. add `toc: false`

```mdx
---
title: API
description: Welcome to the API reference overview page.
toc: false
---
```
3. Expect right sidebar - table of contents - to be hidden.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Sonoma
 - Browser [e.g. brave]
 - Version [e.g. 1.62.162]

**Comment by ryanwaits** [comment]
> **NOTE:** i pulled down your official docs and the `toc` flag works just fine, so not exactly sure what my configuration is missing 🤔

**Comment by fuma-nama** [comment]
It is not a default feature, you have to add a field to the document schema and disable the toc via https://fumadocs.vercel.app/docs/ui/blocks/page#table-of-contents
