### ISSUE TITLE
feat: add `pick` and `omit` options to `<AutoTypeTable />`

### ISSUE THREAD

**Issue by juliusmarminge** [fuma-nama/fumadocs#269]
I love the idea of the auto type table, but sometimes the type can be a bit verbose (perhaps nested objects etc) that i'd like to document in a different way. would be nice to have it a bit more configurable

- A `pick` option, that lets you pick what properties of the type should be documented
- A `omit` option, that lets you omit certain properties

For example, let's say we have this type:

```ts
export interface MyInterface {
  foo: string;
  bar: number;
  __qux: boolean; // maybe this is an internal prop we don't wanna document
}
```

We could generate a table with only `foo` and `bar` like

```tsx
<AutoTypeTable name="MyInterface" pick=["foo", "bar"] />
// or 
<AutoTypeTable name="MyInterface" omit=["__qux"] />
```

Perhaps it'd also be nice with an "override" that let's you override what's returned from the compiler, e.g.

```tsx
type MyRouter = ...;

export interface MyInterface<TEndpoint extends keyof MyRouter> {
  foo: string;
  bar: number;
  qux: TEndpoint;
}

<AutoTypeTable 
  name="MyInterface" 
  overrides={{
    qux: {
      type: "keyof MyRouter", // Compiler gives TEndpoint which might not be very easy to understand what it is
    }
  }}
/>
```

Overrides could be seen like plugging in the normal TypeTable into the AutoTypeTable

**Comment by fuma-nama** [comment]
The `omit` and `pick` feature seems kinda pointless to me, you can always use the built-in utilities (`Pick<T>` etc) instead. I'll prefer an annotation for the override feature.

**Comment by juliusmarminge** [comment]
What do you mean i can use the built in? I need the type to be there on the actual type i just dont want it on the docs.

Are you saying i can do 

```tsx
<AutoTypeTable name="Pick<MyInterface,'foo'>" />
```

To be clear i dont want to omit the type in the lib, just the docs

**Comment by fuma-nama** [comment]
Create a `props.ts` and reimport these types, I want to keep it simple.

```ts
export type MyInterface = Pick<Original.MyInterface, 'foo'>
```

**Comment by juliusmarminge** [comment]
Fair, but then we'd have multiple sources which isn't ideal imo...

**Comment by fuma-nama** [comment]
Despite `omit` and `pick`, `overrides` will be supported in 10.0.0, with a less-hacky way using tsdoc `@remarks` tag.

**Comment by fuma-nama** [comment]
`omit` will be supported with `@internal` tsdoc tag soon

**Comment by juliusmarminge** [comment]
Hmm I don't know if I understand with the approach taken here.

Putting these things in jsdoc means end users will see them when browsing the types, which might cause confusion whether or not they're supposed to use that type.

What I wanted was some way on the documentation level decide what I show, there might be some big generic etc that's just too big to document and i want it.

It's your lib and I don't mean to make up the requirements, just wanted to give you my view on the chosen approach

**Comment by fuma-nama** [comment]
In case it's more recommended to take the initial approach I suggested. Hypothetically, for API types it doesn't make sense to hide any properties unless it's a private field exposed by the API (maybe for some purposes like caching). For a more advanced usage, I'd suggest using utility types instead.
