### ISSUE TITLE
parse `description` tooltip URLs

### ISSUE THREAD

**Issue by juliusmarminge** [fuma-nama/fumadocs#270]
When JSDoc tags have links, it'd be nice if they got parsed and made clickable, like they are in editor:

![CleanShot 2024-02-28 at 21 16 37@2x](https://github.com/fuma-nama/fumadocs/assets/51714798/afb10c9e-cb5f-4286-8e43-1793d60a6e9e)

![CleanShot 2024-02-28 at 21 17 40@2x](https://github.com/fuma-nama/fumadocs/assets/51714798/d5f07c1b-7d9b-48a1-b674-7d76b6f727c8)

**Comment by fuma-nama** [comment]
Will be supported in 10.0.0
