### ISSUE TITLE
[Bug] Next.js 14.1.1 no longer has default export from `next/server`

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#280]
**Describe the bug**
Noticed that my builds were being broken when I upgraded Next.js past 14.1.0.

**To Reproduce**
Try to build a `fumadocs` application with Next.js 14.1.1 or reater.

**Expected behavior**
A successful build! 😄

**Additional context**
Loving `fumadocs` thus far. I was bumping my dependencies to get to 10.0.0 and it looks like bumping Next.js along with it dropped an import that Fumadocs search was using.

I've opened a PR that I believe fixes this issue at #279.

**Comment by fuma-nama** [comment]
Should be fixed with 10.0.1
