### ISSUE TITLE
[BUG] Hovering sidebar with overflow scrolls page body instead of sidebar

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#283]
**Describe the bug**
While hovering the "On this page" sidebar, scrolling with a scroll wheel or touchpad will scroll the page rather than the sidebar.

I discovered this behavior only after making a quite lengthy page with many headers such that the list of headings links was longer than my screen. I went over to the table of contents hoping to scroll to the last heading link to jump to the bottom of the page (the last heading) quickly. 

**To Reproduce**
1. Visit https://fumadocs.vercel.app/docs/ui#root-layout.
2. Shrink your browser window to <500px.
3. Hover the sidebar and try to scroll it.
4. The page body will scroll rather than the sidebar.

**Expected behavior**
I was hoping that the sidebar would scroll given the hovering focus.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc
 - Version: 122.0.6261.94

**Additional details**

I'm happy to see if I can make a PR for this if needed!

**Comment by fuma-nama** [comment]
It was in fact the expected behaviour as it will automatically scroll and center the focused heading by default. 

I'll make some adjustments later, if it's unintuitive.

**Comment by fuma-nama** [comment]
fixed since 10.0.2
