### ISSUE TITLE
Contentlayer is no longer maintained

### ISSUE THREAD

**Issue by sambacha** [fuma-nama/fumadocs#305]
See the GitHub issue here: https://github.com/contentlayerdev/contentlayer/issues/429

There are some suggested replacements in this comment in that issue as well: https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1974928678

**Comment by fuma-nama** [comment]
I have always following the status of Contentlayer, Fumadocs MDX is out as an alternative to Contentlayer as currently there're no drop-in replacements for it. Feel free to suggest, or contribute new content sources.

**Comment by timmeade** [comment]
This is supposed to be a drop in replacment:

https://github.com/timlrx/contentlayer2
