### ISSUE TITLE
`Package subpath './search-algolia/server' is not defined by exports`

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#316]
**Describe the bug**
I'm trying to set up Algolia for search for our documentation and receiving the error from the title.

**To Reproduce**
1. `npx create-fumadocs-app`
2. Follow setup instructions on https://fumadocs.vercel.app/docs/headless/search/algolia
3. Run the script using `npx tsx ./path/to/file`

**Expected behavior**
I'd expect the module to be found so I can add search to my beautiful fumadocs. 😄

**Comment by fuma-nama** [comment]
If you’re using `tsx`, remember to name the extension mts. The package itself is a ESM module.

**Comment by fuma-nama** [comment]
For now it is working good (on both unit tests and the docs site itself), I'll add some instructions for TSX in the docs

**Comment by anthonyshew** [comment]
Oops, of course. Sorry, I didn't even think of that.

I still end up with a cascade of difficulties, though.

Notably, the existing doc has an `allDocs` variable that isn't defined. I'm figuring that is meant to come from a source loader so I went and did `import { getPages } from '../app/source'`. However, that results in:

```
> turbo-site@0.0.0 index-search /turbo-site
> tsx ./scripts/sync-algolia.mts

turbo-site/scripts/sync-algolia.mts:4
import { getPages} from '../app/source';
              ^

SyntaxError: The requested module '../app/source' does not provide an export named 'getBlogPages'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

Fair to assume I'm just pushing the ESM issue down a module? Assuming that's the case, I changed `/app/source` to an `.mts` as well and get:

```
> turbo-site@0.0.0 index-search
> tsx ./scripts/sync-algolia.mts

/turbo-site/app/source.mts:4
import { map } from '@/.map';
         ^

SyntaxError: The requested module '@/.map' does not provide an export named 'map'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by anthonyshew** [comment]
Ah, looking at your code now for your docs site, much different than the things I was assuming. Reworking...

**Comment by anthonyshew** [comment]
Okay, my mistake on the original report. The indexes come from [here](https://fumadocs.vercel.app/docs/mdx/search-index) so no imports needed. Just reading the file off the file system.

So, it looks like I understood what I was meant to do. What ended up helping me was:
- Reading the code for the `www` here in the repo
- This part is vital and not mentioned on the Algolia page: https://fumadocs.vercel.app/docs/mdx/search-index
- I stumbled on this page which got me the frontend: https://fumadocs.vercel.app/docs/ui/search

So maybe adding some links to the doc is the fix here!

**Comment by fuma-nama** [comment]
I have just released a few changes to the [Algolia Search](https://fumadocs-dev.vercel.app/docs/headless/search/algolia) section.

Thank you so much for reporting this issue so that we can fix some potential problems of the docs

**Comment by anthonyshew** [comment]
Looks great! I'm successfully indexing now.

Thank you, once again!
