### ISSUE TITLE
There is no animation if you insert an accordions into an accordions

### ISSUE THREAD

**Issue by sheldygg** [fuma-nama/fumadocs#349]
### To Reproduce

1. Paste this code in some .mdx file
```mdx
import { Accordion, Accordions } from 'fumadocs-ui/components/accordion';
<Accordions>
    <Accordion title={"some accordion"}>
        <Accordions>
            <Accordion title={"some accordion in accordion"}>
                some text
            </Accordion>
        </Accordions>
    </Accordion>
</Accordions>
```
2. Open Accordion with title "some accordion in accordion"

### Current vs. Expected behavior

If you open Accordion which located in Accordions and this Accordions located in outer Accordions, arrow animation will be linked with root Accordions animation instead of have self 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16256
  Available CPU cores: 8
Binaries:
  Node: 21.6.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

UI

### Additional context

![image](https://github.com/fuma-nama/fumadocs/assets/85823514/36a0d812-f069-4a45-9af6-fa607946dbea)
See this, if i open root accordions, attached accordions will be opened with an arrow pointing down

**Comment by fuma-nama** [comment]
Unsupported. This is more likely an anti pattern, you should consider an alternative instead
