### ISSUE TITLE
Modify the shiki highlighter

### ISSUE THREAD

**Issue by arlyon** [fuma-nama/fumadocs#358]
### What problem will this feature address?

I have a DLS that is not built into shiki and I would like to add it. I could create my own highlighter replace the existing code block but I'd like to be able to hook into it and modify it instead.

https://shiki.style/guide/load-lang

Is seems you can call `highlighter.loadLang` to do this.

### Describe the solution you'd like

Some way to get a hold of the shiki highlighter (perhaps in next.config.js?)

### Describe alternatives you've considered

Create my own code block and do the syntax highlighting myself.

**Comment by arlyon** [comment]
Nevermind this is easily accessible from mdxOptions.rehypeCodeOptions.langs. My intellisense was just badly configured.

**Comment by fuma-nama** [comment]
Thanks for your feedback! I'll document the mdx options of `fumadocs-mdx` for future reference.
