### ISSUE TITLE
Custom heading id works not as excepted

### ISSUE THREAD

**Issue by sheldygg** [fuma-nama/fumadocs#365]
### To Reproduce

Add two custom ids in one .mdx file

For example:
```mdx
### Custom Ids [#custom-heading-id]

You can customise the heading id with `[#slug]`.


### Custom Ids [#custom-heading-id1]

You can customise the heading id with `[#slug]`.
```

Open this

### Current vs. Expected behavior

If in one .mdx file you was have more that one custom id, this feature will be work only for first one.

![image](https://github.com/fuma-nama/fumadocs/assets/85823514/9f0a6580-51e5-4d68-b077-baf0d77566d2)

### Provide environment information

```bash
Latest versions of your packages
fumadocs-core@11.0.8
fumadocs-mdx@8.2.16
fumadocs-ui@11.0.8
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
I can’t reproduce the problem on core 11.0.8, could you provide a reproducible repository?

**Comment by sheldygg** [comment]
> I can’t reproduce the problem on core 11.0.8, could you provide a reproducible repository?

Sure, https://github.com/sheldygg/mre_fumadocs

**Comment by fuma-nama** [comment]
Found the problem, it seems like you have older version of fumadocs mdx installed, it uses `fumadocs-core@11.0.7 which contains a bug in regex. NPM installs the both (11.0.7 and 11.0.8) causing it to pick the wrong version of core.

**Comment by sheldygg** [comment]
Yes, after instaslling fumadocs-mdx@8.2.17 this feature works good, thanks!
