### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Shubham-4467** [fuma-nama/fumadocs#391]
### What problem will this feature address?

I'm considering switching from `Nextra` to `Fumadocs`, but there's still room for UI improvement in `Fumadocs`.

Here are some specific suggestions:

1. Add Proper `Margins` in Sidebar Lines:

`Fumadocs` sidebar lines lack proper top and bottom margins.
In Nextra's sidebar, for reference, there's clear spacing between lines.
![image](https://github.com/fuma-nama/fumadocs/assets/64977436/70fd8d11-0f1a-47bd-9c58-82330437e57a)

As an example, in `Fumadocs`, the line touches "Components" directly.
![image](https://github.com/fuma-nama/fumadocs/assets/64977436/3c336542-e3ad-4558-ac52-e4197373cae5)

Similarly, a bottom margin should be added so the line sits slightly higher. 

2. Sidebar Link Alignment:

`Nextra` displays sidebar links inline.
![image](https://github.com/fuma-nama/fumadocs/assets/64977436/34901618-1c98-418b-a02a-08c8835e19d9)

In `Fumadocs`, they appear non-inline.
Ideally, `Fumadocs` links should also be displayed inline for consistency.
![image](https://github.com/fuma-nama/fumadocs/assets/64977436/a2a1b9fd-8647-40b3-91d3-7489df62ada6)

By implementing these changes, `Fumadocs` can achieve a more visually appealing and user-friendly interface.

### Describe the solution you'd like

Given above already

### Describe alternatives you've considered

Given above already

**Comment by fuma-nama** [comment]
About 1. It’s better to remove the margins in my opinion as it groups its child items better
And a fix for 2. is coming, check https://fumadocs-dev.vercel.app/docs/ui/comparisons

**Comment by fuma-nama** [comment]
Fixed in 11.1.3
