### ISSUE TITLE
Feedback system for documentation

### ISSUE THREAD

**Issue by Seokhyeon315** [fuma-nama/fumadocs#397]
### What problem will this feature address?

The main reason we want to build our own documentation project is to provide accurate and latest information to the users. But since we are humans, we might make mistakes such as typo or wrong information and we might miss the mistakes. 

### Describe the solution you'd like

I wish there is a feature for feedback system on right side of the documentation for every page. 

### Describe alternatives you've considered

Maybe create another api for feedback or simply form submission external links as a feedback system?

### Additional context

Thanks for building this project. This is by far the best documentation project that is compatible with Next JS app router. I hope this project will be continued and improved more.

**Comment by fuma-nama** [comment]
I'll just recommend using Github Issues or any API services if your docs is for non-technical people, building an API for feedback needs a database, realtime notification system and a full-powered rich editor + UI. This is obviously too much for a docs framework. Taking some reference from Next.js docs or Nextra, you can add a button to report docs issues (which redirects users to Github Issues template).
