### ISSUE TITLE
fail render twoslash in MDX file

### ISSUE THREAD

**Issue by ZoroZh** [fuma-nama/fumadocs#424]
### To Reproduce

Hi @fuma-nama ,thank you for your great job. I'm trying to use fumadocs-twoslash. i followed UI-doc .but i just render a raw code block.

![image](https://github.com/fuma-nama/fumadocs/assets/38368479/3678c494-afa7-4345-9daf-ff04ac2a05e4)

![image](https://github.com/fuma-nama/fumadocs/assets/38368479/af539073-d977-42f3-8929-46ad3ed7c701)

![image](https://github.com/fuma-nama/fumadocs/assets/38368479/394d98a7-7995-4df0-a079-546722638c78)

![image](https://github.com/fuma-nama/fumadocs/assets/38368479/770100bf-544b-43a8-be7d-4c2ba52cab4f)

### Current vs. Expected behavior

can you help me out .

### Provide environment information

```bash
pnpm:
"next": "14.2.3",
"tailwindcss": "^3.4.1",
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
rename your `mdxOptions.transformers` to `mdxOptions.rehypeCodeOptions.transformers`. You probably made a misttake when copying the example code, because the example in the docs is correct.
