### ISSUE TITLE
[Bug] Using backticks for inline code breaks hashlinks/table of contents

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#425]
### To Reproduce

In this repo, I edited `./apps/docs/ui/index.mdx` so that the first heading uses some inline code. Conditions for buggy behavior:
- Wrapping the whole title in backticks (e.g. `Introduction`) removes the hashlink ID from the page HTML and removes the heading from table of contents.
- Partially wrapping the title (e.g. `Introductio`n) results in the hashlink ID being restored - but the table of contents entry only shows the "n"

### Current vs. Expected behavior

I would expect the hashlink to maintain its ID and the table of contents entry to show the text content of the inline code and text.

### Provide environment information

```bash
Don't think it will matter but following instructions. 😄

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.11.0
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

MDX

**Comment by fuma-nama** [comment]
I see, I will fix it soon. For now, you can use [Custom Heading Ids](https://fumadocs.vercel.app/docs/headless/mdx/toc#custom-heading-id) as a temporary fix. Thanks for pointing it out!

**Comment by fuma-nama** [comment]
Will be fixed in v12

**Comment by fuma-nama** [comment]
Fixed since v12
