### ISSUE TITLE
建議添加min-h-screen

### ISSUE THREAD

**Issue by yyrc** [fuma-nama/fumadocs#428]
設置footer後，發現如文章過短，pc瀏覽起來不是很好看，參考了下nextra，發現nextra設置了Min-Height，建議为页面添加`min-h-screen`，限制最小高度，瀏覽器瀏覽看起來更舒服點。

如nextra、docusaurus都有类似调整
```
<article class="nx-w-full nx-break-words nextra-content nx-flex nx-min-h-[calc(100vh-var(--nextra-navbar-height))] nx-min-w-0 nx-justify-center nx-pb-8 nx-pr-[calc(env(safe-area-inset-right)-1.5rem)]"></article>
```

**Comment by fuma-nama** [comment]
To avoid global style pollutions as much as possible, Fumadocs UI doesn't change the default body height. You can add the `min-h-dvh` utility class to body, but it won't be added by default.
