### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by fuma-nama** [fuma-nama/fumadocs#430]
### What problem will this feature address?

I personally prefer removing the navbar in a docs site, because its navigation functionalities can be replaced with a sidebar, and I love minimal design.

Also, the default UI doesn't work with multiple page trees well, you'll have to write your own switch to navigate between page trees (similar to the main site). It would be nice if it is implemented by default.

### Describe the solution you'd like

Make navbar only shown on mobile devices.

### Describe alternatives you've considered

N/A

**Comment by yyrc** [comment]
現在的ui感覺已經很好了，很漂亮的ui。
提幾個建議：
1. 統一下頁面和文檔模式下navbar的ui。  
原ui
![1](https://github.com/fuma-nama/fumadocs/assets/99700709/d5429204-d26b-42b5-9f8d-fa1ca730ba4f)
建議修改為
![2](https://github.com/fuma-nama/fumadocs/assets/99700709/2415637e-42b0-4c4e-811d-3f65a804923f)
和文檔一樣的ui，看起來更舒服。
2. mdx頁面轉移到`content`目錄下  
目前的頁面只能在`app\(home)\xx\page.mdx`，對於強迫症患者，更喜歡把`page.mdx`轉移到`content`目錄下，例如`content\page\xx\page.mdx`或`content\page\xx.mdx`，統一存放頁面。
3. 默認把layout.config.tsx獨立出來  
當設置文檔和頁面時，還是需要對layout都設置一次config，把layout.config.tsx獨立出來，默認加入到examples，對新手更友好，不用參考官方文檔。
4. fumadocs相比nextra，其實門檻更高，當然這可以當做fumadocs的一種特色。但我相信簡潔易用會走的更遠。

請原諒我不是個程序員，也不是很懂代碼，但很喜歡研究，無法提供代碼，只提些意見把，希望fumadocs越來越好。

**Comment by fuma-nama** [comment]
the suggestion 2 is not possible because of the limitations of Next.js App Router. What a Webpack plugin can do is pretty limited. 
And we are not planning to get another domain (yes I'm lazy), the current site might not be accessible from China mainland.

It would be better if you can use English here, so that the other subscribers on this thread can read it without a translator.

**Comment by fuma-nama** [comment]
Current plannings:

1. Implement `RootToggle`, so that you can have a built-in way to let users switch between page trees.
2. Remove navbar except for non-docs layout, this will be a breaking change and feedback might be very polarized.

**Comment by fuma-nama** [comment]
We are releasing v12, more changes will be made as we receive more feedback.

**Comment by changeelog** [comment]
Consider adding icons in the same style for other subsections. Currently only UI has its own icons.

![core](https://github.com/fuma-nama/fumadocs/assets/135520429/814e35f9-b23d-44a2-81aa-31af86294565)
![mdx](https://github.com/fuma-nama/fumadocs/assets/135520429/efac58ab-6963-474f-8afe-c2d62a26d1c9)
![ui](https://github.com/fuma-nama/fumadocs/assets/135520429/b245de0d-f741-4abc-a3a1-ef787296504c)

For icons sources we could look up here
[https://github.com/iconify/iconify](https://github.com/iconify/iconify)

Speaking of MDX section, I like those icons:
- Getting Started - maybe the same icon from UI section
- Image Optimization - [https://icon-sets.iconify.design/carbon/image/](https://icon-sets.iconify.design/carbon/image/)
- Last Modified Time - [https://icon-sets.iconify.design/carbon/time/](https://icon-sets.iconify.design/carbon/time/)
- Generate Search Indexes - This one is kinda hard to choose. Maybe this one - [https://icon-sets.iconify.design/carbon/search-advanced/](https://icon-sets.iconify.design/carbon/search-advanced/)

Speaking of Core section, I like those icons:
- Quick Start - maybe the same icon from UI section? Also maybe the naming of this specific section should be consistent across the website? For now we have: 2x Quick Starts and Getting Started
- Page Conventions - [https://icon-sets.iconify.design/carbon/document/](https://icon-sets.iconify.design/carbon/document/)
- Page Tree - I dont kinda like this one, but others seem to make no sense. [https://icon-sets.iconify.design/carbon/tree-view/](https://icon-sets.iconify.design/carbon/tree-view/)
- Internationalization - [https://icon-sets.iconify.design/carbon/flight-international/](https://icon-sets.iconify.design/carbon/flight-international/)

**Comment by fuma-nama** [comment]
I think it's better to be transferred to the docs rewrite issue.

**Comment by yyrc** [comment]
> ### What problem will this feature address?
> I personally prefer removing the navbar in a docs site, because its navigation functionalities can be replaced with a sidebar, and I love minimal design.
> 
> Also, the default UI doesn't work with multiple page trees well, you'll have to write your own switch to navigate between page trees (similar to the main site). It would be nice if it is implemented by default.
> 
> ### Describe the solution you'd like
> Make navbar only shown on mobile devices.
> 
> ### Describe alternatives you've considered
> N/A
> 
> ### Additional context
> _No response_

I tried version 12, but I feel that modifying the UI this time is not a good idea. The UI doesn't look very coordinated. For me, the original Navbar was more convenient to use.~

**Comment by fuma-nama** [comment]
This navbar removal is the priority of this update and I won't reverse the change unless I found a serious problem or reason. 

It separated the docs layout from other pages and reduced elements that aren't related to docs, which might feel weird if you were accustomed to the previous design. 
But to me, playing with Yeecord and the official docs site, it feels better on large MDX pages. 

Of course, this is pretty subjective and I'll see if there's anything else I can improve.

**Comment by fuma-nama** [comment]
I'm closing the issue. If you have any suggestions about the UI, don't hesitate, open a new post in Discussion and share your thoughts with me!
