### ISSUE TITLE
Add translations for “theme”~

### ISSUE THREAD

**Issue by yyrc** [fuma-nama/fumadocs#431]
![微信图片_20240607093403](https://github.com/fuma-nama/fumadocs/assets/99700709/ad549731-1730-462e-a8e8-866dc449fd26)
It is recommended to add a translation of this word~

**Comment by fuma-nama** [comment]
Hmm why close it? It's a pretty good suggestion, we will be supporting it on v12.

**Comment by fuma-nama** [comment]
Supported since v12
