### ISSUE TITLE
Failure in project initialization

### ISSUE THREAD

**Issue by Jacques2Marais** [fuma-nama/fumadocs#469]
### To Reproduce

1. Run `npx create-fumadocs-app` in the terminal to create a new Fumadocs project
2. Complete the steps as requested by the CLI

### Current vs. Expected behavior

Following the steps from the previous section, I expected a new project to be created, but a failure was produced by npm:

<img width="1217" alt="image" src="https://github.com/fuma-nama/fumadocs/assets/88091427/9ed7bb96-ff04-4a97-ab45-347a2fc3641d">

### Provide environment information

```bash
(ran outside project since project could not be created)

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 21.7.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-fumadocs-app)

**Comment by fuma-nama** [comment]
My mistake, after moving `fumadocs-core` to peer dependency, the latest release of Fumadocs MDX with correct peer dependency versions isn't released in time. It should be fixed now
