### ISSUE TITLE
Built-In Support for GitHub Content Loading

### ISSUE THREAD

**Issue by kijv** [fuma-nama/fumadocs#479]
### What problem will this feature address?

Fetching files from GitHub repository and supplying them for the docs (ex. private app with public docs)

### Describe the solution you'd like

A helper function supplied by `mdx-remote` may be the most plausible solution, although it can require more manual configuration. It may permit more freedom than a whole new abstraction for content loading, but can also be limiting in its nature of simplicity.

### Describe alternatives you've considered

Implementing a `github` object option in config of the `mdx-remote` package. Alternatively, a new `github` package which acts as a new content loader instead of local files, `contentlayer`, or manual `next-mdx-remote`

### Additional context

This feature is mostly to eliminate redundancy among users (and me) needing to implement a remote source via GitHub.

> I’m also brainstorming the best course of action for local development. Especially if they want updates realtime (instead of having to push to GitHub)

Target goal of this is serving files from a GitHub repository in a more simpler (and more straightforward) manner than `contentlayer`/`next-mdx-remote`.

**Comment by fuma-nama** [comment]
Yes I have planned for this when working on MDX remote. I'm kinda busy right now, so it may take me longer to come up with a solution.

My plans are: Add a function for fetching content, generate the page tree, and hot-reload after updating local content. Welcome to suggest more ideas.

**Comment by kijv** [comment]
I'm open to drafting a PR with a possible solution

**Comment by fuma-nama** [comment]
Thanks! I have implemented the page tree generation and GitHub file API, but hot reload is yet to be implemented, also I would like to figure out how the workflow should be work (e.g. use local file system in dev mode and GitHub on production?)

**Comment by fuma-nama** [comment]
> I think to optimize file fetching, fetch the directory first

I would prefer using the local file system for page trees, so we don't have to fetch directories from GitHub (which can easily reach the rate limit of their API). People can setup a script on deploy step to generate page trees before building the app in production mode.

Dev Mode: 100% rely on local files
Production Mode: Build page tree from local file system, but fetch file content from GitHub.

**Comment by fuma-nama** [comment]
But building page trees from local file system means after deploying it, you cannot update the page tree dynamically on runtime, e.g. using `revalidate` to update the page tree.

You can also generate a `page-tree.json` file on each commit to avoid fetching directories, this is be done with existing tools.

**Comment by fuma-nama** [comment]
The `fetch` cache + revalidate is enough, we can store page trees in a JSON file and fetch that using GitHub API. 

Since building page tree needs the content of all files inside directory, we should generate the JSON file using scripts before committing to Git.

**Comment by fuma-nama** [comment]
Thanks for recommending this nice API we could use. I think the problem is how do we *read* the frontmatter of all files inside directory, especially the MDX remote package is aimed to solve the problem of handling a huge amount of MDX documents, it must be capable to handle that while GitHub API cannot allow reading thousands of files every hour.

**Comment by fuma-nama** [comment]
I'll keep my idea aforementioned: Store a single `page-tree.json` in the repo, and update it with a script every commit or deployment.

**Comment by fuma-nama** [comment]
I see, it would be nice if we can implement this workflow on the MDX remote package.

**Comment by fuma-nama** [comment]
You can always use local file content in dev mode, and it automatically use the remote files in production mode

**Comment by fuma-nama** [comment]
The docs for this is now available, you can read it for further details.
https://fumadocs.vercel.app/docs/headless/remote/github
