### ISSUE TITLE
Option to have OpenAPI generator to generate separate page for each request.

### ISSUE THREAD

**Issue by kyrylolvov** [fuma-nama/fumadocs#494]
### What problem will this feature address?

Right now OpenAPI generates one page with many requests.

### Describe the solution you'd like

Would be nice to have it like Mintlify does, where they have each request as separate page

### Describe alternatives you've considered

https://demo.mintlify.app/api-reference/endpoint/get

**Comment by fuma-nama** [comment]
I think considering the design of Fumadocs UI is more compact than Mintlify's, honestly it doesn't look good with our design.

![image](https://github.com/fuma-nama/fumadocs/assets/76240755/1f7f978f-f1e6-4c29-94eb-85d39f5a9186)

**Comment by fuma-nama** [comment]
I'll add it to the next release, but the default value will still be `page`.

**Comment by fuma-nama** [comment]
Released!
