### ISSUE TITLE
Wrong url with i18n

### ISSUE THREAD

**Issue by alehano** [fuma-nama/fumadocs#505]
### To Reproduce

Add i18n support and set baseUrl. 
I use third party **next-intl** becase use fumadocs as a part of the website. So I'm not using `createI18nMiddleware` but using **next-intl**'s one.

### Current vs. Expected behavior

pages has url: /blog/fr/page
should be: /fr/blog/page

in loader I have baseUrl: "/blog"

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.9.0
Relevant Packages:
  next: 14.2.3 // There is a newer version (14.2.4) available, upgrade recommended! 
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.3.3
Next.js Config:
  output: N/A
 ⚠ There is a newer version (14.2.4) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
This should be fixed on a previous release, do you sure you are using the latest version of Fumadocs?

**Comment by alehano** [comment]
Indeed, it was old version. Thanks a lot.
