### ISSUE TITLE
Open API: Only hostname is being extracted to the example request

### ISSUE THREAD

**Issue by Siumauricio** [fuma-nama/fumadocs#516]
### To Reproduce

1. Use the Open API generator
2. Use this open api schema https://github.com/Dokploy/docs/blob/main/api.json
3. Run `node generate-docs.mjs` to generate the api reference

### Current vs. Expected behavior

Identified Issue
In the cURL and JavaScript examples generated by the OpenAPI generator, the request URL is incorrectly shown as `http://localhost:3000/admin.one`, when it should be `http://localhost:3000/api/trpc/admin.one`.

Expect: 

I expect to see the request url as `http://localhost:3000/api/trpc/admin.one` instead of  `http://localhost:3000/admin.one`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g Contentlayer, OpenAPI, Typescript DocsGen)

### Additional context

I check mintlify and verify if the baseURL is respected and the path is complete not just the hostname.

**Comment by fuma-nama** [comment]
Fixed on 3.1.3
