### ISSUE TITLE
i18n Locale Path Prefixing

### ISSUE THREAD

**Issue by unsphere** [fuma-nama/fumadocs#528]
### What problem will this feature address?

It would be great if we can hide the locale prefix for defaultLocale, e.g. if defaultLocale = en and locales = ['en', 'de'], then /en should be hidden for paths like so /docs, but if locale is set to 'de' then /de/docs should be used.

### Describe the solution you'd like

Add desired config options to createI18nMiddleware, e.g. prefixDefault = false or maybe if someone wants to hide the path prefix at all: noPrefix = false

### Describe alternatives you've considered

createI18nMiddleware config options like [next-i18n-router](https://github.com/i18nexus/next-i18n-router/tree/main?tab=readme-ov-file#config-options)

**Comment by fuma-nama** [comment]
I think the `noPrefix` option of next-i18n-router isn't quite clear, they actually use `NextResponse.rewrite` to *hide* the locale prefix from path name, since Next.js doesn't support optional dynamic route (which makes sense). 

will implement that later

**Comment by fuma-nama** [comment]
Done, welcome to leave some feedback about the new API!

**Comment by unsphere** [comment]
> Done, welcome to leave some feedback about the new API!

Thanks for the quick implementation! Already found a bug here: [https://github.com/fuma-nama/fumadocs/issues/542](https://github.com/fuma-nama/fumadocs/issues/542)
