### ISSUE TITLE
i18n hideLocale baseUrl redirect issue

### ISSUE THREAD

**Issue by unsphere** [fuma-nama/fumadocs#542]
### To Reproduce

Use the new version 12.3.2 introduced **hideLocale** prop in **createI18nMiddleware**:
```js
createI18nMiddleware({
  languages,
  defaultLanguage,
  hideLocale: 'default-locale',
})
```
Use a **baseUr**l in the **loader**:
```js
export const { getPage, getPages, getLanguages, pageTree } = loader({
  baseUrl: '/docs',
  rootDir: 'docs',
  languages,
  source: createMDXSource(map),
});
```

### Current vs. Expected behavior

Notice that all links and using the locale switcher will result in a redirect to the homepage without respecting the baseUrl.

If en is defaultLocale, for example:

- Switching from chinese to english in the locale switcher will redirect to / instead of /docs
- Visiting /en/docs/faq will redirect to / instead of /docs/faq, same for the docs homepage /en/docs will redirect to /

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 21.6.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core

### Additional context

[https://github.com/fuma-nama/fumadocs/issues/528](https://github.com/fuma-nama/fumadocs/issues/528)

**Comment by fuma-nama** [comment]
Thanks for reporting it, it turns out to be a problem of Fumadocs UI, the language toggle is unable to detect whether the current locale prefix is hidden or not, so it replaced the wrong segment. It would be a little bit tricky to fix since `locale` wasn't a required prop, but now it's necessary to detect that. I'll fix the language toggle, and improve the docs to include that part.

**Comment by fuma-nama** [comment]
Done, the problem should be fixed now
