### ISSUE TITLE
Fumadocs UI v13 Roadmap

### ISSUE THREAD

**Issue by fuma-nama** [fuma-nama/fumadocs#548]
### What problem will this feature address?

**CSS Styles Pollution:** Fumadocs UI overrides the default border color, and adds 12+ Tailwind CSS colors which may conflict with the current Tailwind CSS configuration of the app. While this may benefit the devs who want to share the same design system with the docs, some may prefer their own design system over other places.

### Describe the solution you'd like

**CSS Styles Pollution:**
- Add `fd-` prefix to Fumadocs UI added colors, animations, and utilities.
- Add styles to `prose-fd` instead of overriding `prose` directly.
- No longer override the default `container` styles of Tailwind CSS.
- ~~Allow devs to opt-out of Fumadocs UI provided default border color on other places. (e.g. disable the default border color added by Fumadocs UI with `no-fc-border` class)~~ (This can be done with a simple `[&_*]:border-some-color` class)

### Describe alternatives you've considered

N/A

**Comment by jonathanwilke** [comment]
This sounds like a very good plan. As I am using fumadocs right now directly in my web app which already has some defined color variables, the fumadocs components don't look as expected out of the box.

For example I seem to be using the secondary color differently then you expect here, so the search button looks a bit awkward. 

<img width="420" alt="Bildschirmfoto 2024-07-24 um 07 01 08" src="https://github.com/user-attachments/assets/74a4f094-3d2a-4743-816f-d5781ad0b47c">

Having prefixed classes would be really helpful, so the styles don't get into the way of the rest of the app.

**Comment by fuma-nama** [comment]
Surely! I've also received some similar issues from others, I'll work in that once I have the time to refactor the codebase.

**Comment by jonathanwilke** [comment]
No hurry man! You are doing an amazing job with fumadocs already and I am really thankful for all the effort you put into this!

**Comment by thebadking** [comment]
Still having issues with this, how to solve it
