### ISSUE TITLE
 DynamicSidebar is not defined

### ISSUE THREAD

**Issue by changeelog** [fuma-nama/fumadocs#559]
### To Reproduce

1. Clone the fork [https://github.com/changeelog/fumadocs](https://github.com/changeelog/fumadocs)
2. Install + build deps
3. Run dev server and go to any /docs page

### Current vs. Expected behavior

Curr: Breaks due to a missing import error
Expected: Work correctly

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
  Available memory (MB): 7992
  Available CPU cores: 4
Binaries:
  Node: 21.6.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Core

### Additional context

The thing on the screenshot below [refers us here](https://github.com/fuma-nama/fumadocs/blob/996af262e2d8ecc9deb2e2b6ddcf3d46759a66f1/packages/ui/src/layout.tsx#L159):

![Screenshot_2](https://github.com/fuma-nama/fumadocs/assets/135520429/31adcb51-7201-4c7f-bd41-d3d60cbc6194)

[https://github.com/fuma-nama/fumadocs/blob/996af262e2d8ecc9deb2e2b6ddcf3d46759a66f1/packages/ui/src/layout.tsx#L159](https://github.com/fuma-nama/fumadocs/blob/996af262e2d8ecc9deb2e2b6ddcf3d46759a66f1/packages/ui/src/layout.tsx#L159)

Seems like those imports are not included by the bundle. For reference take a look at nav declaration

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/84ddba24-b7ee-4af0-8be3-6482570c0930)

And it has its own import right there but we dont have such thing for all this components `TreeContextProvider, DynamicSidebar, SubNav, LinksMenu, Sidebar, ThemeToggle`

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/522ab050-9cb4-4611-b168-9efe7fce9da3)

VSCode IntelliSense also has something to say

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/4b891b18-7075-4d9c-95ea-78589a6820fd)

**Comment by fuma-nama** [comment]
That's weird, after bundling packages, it should do a trick to inject imports of client components to the output. Is there any errors when build the packages?

**Comment by changeelog** [comment]
No, it bundles perflectly fine, and I get no errors while navigating through index page, but when I come to /docs/anything - I get this

**Comment by changeelog** [comment]
Hold up

**Comment by changeelog** [comment]
At this point I have no clue, bundler related problems (if this is one of them) are so painful to solve

**Comment by fuma-nama** [comment]
![image](https://github.com/fuma-nama/fumadocs/assets/76240755/9685e0b6-e6e0-4521-a58e-d6829342d038)

Can you see this in the build output of Fumadocs UI?

**Comment by changeelog** [comment]
> ![image](https://private-user-images.githubusercontent.com/76240755/345342000-9685e0b6-e6e0-4521-a58e-d6829342d038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDgxNTYsIm5iZiI6MTcyMDAwNzg1NiwicGF0aCI6Ii83NjI0MDc1NS8zNDUzNDIwMDAtOTY4NWUwYjYtZTZlMC00NTIxLWE1OGUtZDY4MjkzNDJkMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYWZjOWEyOGZjMDI4OGQxZGVhZmI1Zjc0NGVkYTIzNDJmYTkxNzU4ZjhiMmY1NzIzNmRjYjcyZmQ1ZDVmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4PrJbDbfQinAjTVOKeqVsmF0FdWXdLjs7_1uUX3tzU)
> 
> Can you see this in the build output of Fumadocs UI? Running `pnpm clean && pnpm build ./packages/*` should give this result, which is injected by our custom script

I don't have those lines for some reason

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/bdbe5171-1afa-4ee0-9996-e938c18fcfc3)

**Comment by changeelog** [comment]
this is weird, but adding this lines manually

For `layout.js`

```
import {
  TreeContextProvider,
  DynamicSidebar,
  SubNav,
  LinksMenu,
  Sidebar,
  ThemeToggle,
} from './docs.client';
```

And this for `page.js`

```
import {
  TocProvider,
  TocPopover,
  Breadcrumb,
  LastUpdate,
  Footer,
  Toc,
} from './page.client';
```

It solved the issue, anyways this is so weird

**Comment by fuma-nama** [comment]
Yes and this should be generated by the custom script in tsup configuration, I am honestly not sure about the actual problem, hope it's related to Node.js versions or file system.

**Comment by fuma-nama** [comment]
I'm developing this project on my windows 11 PC and MacBook, it should work on windows system

**Comment by changeelog** [comment]
> I'm developing this project on my windows 11 PC and MacBook, it should work on windows system

I don't think it's about the OS, in general there shouldn't be anything so special about the OS specifically that would break the behavior.

Seems like a weird caching issue to me, I have no clue how to prove that tho. Tried using `--force` optino to ignore existing cached artifacts and re-execute all tasks, yet the behavior is still the same

**Comment by fuma-nama** [comment]
it's about the `tsup.config.ts` file, we added a script after build successful to inject imports for client components. It should be executed after successful compilation, can you do some debug on your side?

**Comment by fuma-nama** [comment]
I made it a dynamic import, meaning that it's now conditionally loaded. When users disable collapsible sidebar, it won't be loaded into the client bundle. This would also change the output of build.
