### ISSUE TITLE
Children property for sidebar

### ISSUE THREAD

**Issue by cosigyn** [fuma-nama/fumadocs#562]
### What problem will this feature address?

When using the navbar, I have added a 'log in' button using the children property. I can't seem to find a way to add custom buttons with the sidebar.

![image](https://github.com/fuma-nama/fumadocs/assets/77410185/7eecbd3d-63dd-41ce-a1bd-2c20f94925e4)
```tsx
  const docsOptions: BaseLayoutProps = {
    nav: {
      enabled: true,
      title: "Clanware",
      children: (
        <div className="flex justify-end w-full">
          {user ? (
            <form action={logout}>
              <button className="px-2 border rounded-md">Log Out</button>
            </form>
          ) : (
            <form action="/login/roblox">
              <button className="px-2 border rounded-md">Log In</button>
              </form>
          )}
          
        </div>
      ),
    },
    links: [
      {
        text: "Documentation",
        url: "/docs",
        active: "nested-url",
      },
    ],
  };
  ```

### Describe the solution you'd like

Add a property 'children' to the sidebar.

### Describe alternatives you've considered

Allow disabling the sidebar entirely, so the navbar is always visible.

**Comment by fuma-nama** [comment]
I would suggest the banner property: https://fumadocs.vercel.app/docs/ui/blocks/layout#sidebar
Or using Links API instead

**Comment by fuma-nama** [comment]
After considering, I will close this issue. the name `children` isn't clear enough, we don't know where the children should be placed, and existing APIs like `banner` and Links API should suit your use case.
