### ISSUE TITLE
MDX Remote: Failed to fetch info of private repositories

### ISSUE THREAD

**Issue by cosigyn** [fuma-nama/fumadocs#564]
### To Reproduce

1. Create a fumadocs project with `npx create-fumadocs-app`
2. Select fumadocs mdx as content source
3. Follow setup [here](https://fumadocs.vercel.app/docs/headless/remote/github)
4. console.log the output of the `loader` function
5. Run `next build` and `next start`
6. Attempt to access a valid file in the github repo on your fumadocs app

### Current vs. Expected behavior

The pageTree is empty and the output of the loader function shows the content is null, unless you set `keepContent: true`. 
The generated blobUrl is invalid and a 404 response occurs.

The fumadocs responds a 404 to the browser.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 12123
  Available CPU cores: 4
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core, MDX

### Additional context

The repo is private using a github PAT as the access token. It is definitely successfully accessing the repo as the frontmatter values are in the outputted message.

**Comment by fuma-nama** [comment]
> The pageTree is empty and the output of the loader function shows the content is null, unless you set keepContent: true.

You must use the resolve file function to obtain file content, it's not included into the loader output to avoid high memory usages.

I think the empty tree page is probably caused by your configurations, please provide a producible example.

**Comment by cosigyn** [comment]
I have published my code here: https://github.com/cosigyn/clanware-docs/blob/main/app/source.ts

I extracted things from the main function to try and get a clearer picture of what's going on.

Also a key difference of my repo is that the docs endpoint is set to `/` rather than `/docs`

The content is in a different repo, 
![image](https://github.com/fuma-nama/fumadocs/assets/77410185/a9ea592b-6a48-4700-8492-e13f9b1ac468)

**Comment by fuma-nama** [comment]
Please use a public repository for content, I have to take a look into your documentation repo.

**Comment by cosigyn** [comment]
It seems like making it public made it work as expected. But is there no way I can do this with a private repo like providing a token in the API requests? I would like to have authorization required for certain docs.

**Comment by fuma-nama** [comment]
Do you sure you have given enough permissions to the PAT? Private repos need extra permissions

**Comment by fuma-nama** [comment]
The following API endpoints are used:

https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28
https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28#get-a-blob

**Comment by cosigyn** [comment]
Yes, I have given the `Contents` permission.

**Comment by fuma-nama** [comment]
Not sure if it's the problem of GitHub API, could you test the API endpoint: https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#get-a-tree with your own PAT? Fetching my private repos works as expected. 
Also check if the `treeSha` is correct.

**Comment by cosigyn** [comment]
Ok - it's working now, docs are available while its private. But the API had always been working as I saw it in the console logs. I don't know what I changed 🤦
