### ISSUE TITLE
Be able to test APIs in OpenAPI Generated Docs

### ISSUE THREAD

**Issue by gaokevin1** [fuma-nama/fumadocs#566]
### What problem will this feature address?

I want to be able to actually send JSONs and test the APIs that are mentioned in the docs. We have a lot of complicated schemas that the APIs are expecting, and being able to alter the JSON request data and send the APIs would be very helpful.

### Describe the solution you'd like

A section underneath the cURL code example, that would allow you to make requests and edit the JSON payload of the request, as well as a section that can show the response from the API as well.

<img width="1263" alt="image" src="https://github.com/fuma-nama/fumadocs/assets/32936811/620c6352-ae0a-41e0-92f6-1fe9c6fa1f27">

### Describe alternatives you've considered

I think this makes sense, and doesn't really have a good alternative to be honest.

**Comment by fuma-nama** [comment]
We already have a PR to implement the API playground, it is still in development.

**Comment by gaokevin1** [comment]
That's awesome! Any idea how long it might be until it's available?

**Comment by fuma-nama** [comment]
I'm uncertain about that, perhaps 1 week

**Comment by gaokevin1** [comment]
@fuma-nama we're planning to use this feature in our docs migration. Not sure how much is left to do, but how realistic is it to merge this feature by the beginning of next week?

**Comment by fuma-nama** [comment]
Unlikely, the playground still have problems under complex schemas and need more tests

**Comment by fuma-nama** [comment]
Supported, welcome to leave feedback about the new API playground

**Comment by gaokevin1** [comment]
Awesome!!! Thank you!
