### ISSUE TITLE
Setup with content-collections not working

### ISSUE THREAD

**Issue by jonathanwilke** [fuma-nama/fumadocs#571]
### To Reproduce

When I try to set up the fumadocs with content-collections as described in the docs (https://fumadocs.vercel.app/docs/headless/content-collections) I get the following type error:

<img width="1017" alt="Bildschirmfoto 2024-07-06 um 15 45 01" src="https://github.com/fuma-nama/fumadocs/assets/1453455/619638c6-6d34-426b-8857-dd2e76ec44c3">

Any idea what could be the reason or what I am doing wrong?

### Current vs. Expected behavior

The example from the documentation should work.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Thu May 30 21:31:14 PDT 2024; root:xnu-11215.0.31.511.2~1/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
it was related to the `zod` version conflicts with Content Collections, which I have encountered when working on the example.

As a fix, I changed the zod parameter of `createDocSchema` to a generic type. It turns out the result document somehow became `content: unknown`, which caused other type problems.

The type definitions of Content Collections are more complicated than I thought, I'll make a fix about this soon. For now, you can use:
```ts
const docs = defineCollection({
  name: 'docs',
  directory: 'content/docs',
  include: '**/*.mdx',
  schema: (z) => ({
    title: z.string(),
    description: z.string().optional(),
    icon: z.string().optional(),
    full: z.boolean().optional(),
  }),
  transform: transformMDX,
});

const metas = defineCollection({
  name: 'meta',
  directory: 'content/docs',
  include: '**/meta.json',
  parser: 'json',
  schema: (z) => ({
    title: z.string().optional(),
    pages: z.array(z.string()).optional(),
    defaultOpen: z.boolean().optional(),
  }),
});

export default defineConfig({
  collections: [docs, metas],
});
```

**Comment by fuma-nama** [comment]
Released a hotfix, you may give it a try. If it causes other type problems, install `zod` to your workspace, this should fix the problem.

**Comment by jonathanwilke** [comment]
Hey @fuma-nama, thanks for the quick answer! This resolved the type error indeed, but now I get the following error when starting my app:  
<img width="628" alt="Bildschirmfoto 2024-07-07 um 09 08 36" src="https://github.com/fuma-nama/fumadocs/assets/1453455/d6da6606-ab67-45ff-b580-2eacc2318790">

**Comment by fuma-nama** [comment]
You probably specified a directory that doesn't exist

**Comment by jonathanwilke** [comment]
Oh I am such an idiot. Now it's working! 
Sorry to have bothered you with this!

And thanks so much for the great work on fumadocs! I am considering including it per default in my SaaS starter kit [supastarter](https://supastarter.dev).
