### ISSUE TITLE
Search in docs is not working

### ISSUE THREAD

**Issue by jonathanwilke** [fuma-nama/fumadocs#576]
### To Reproduce

Hey I just noticed that the search on https://fumadocs.vercel.app/docs is not working.

<img width="774" alt="Bildschirmfoto 2024-07-07 um 12 02 49" src="https://github.com/fuma-nama/fumadocs/assets/1453455/52d9c15a-59b7-4bd1-854e-1670e68e3be0">

### Current vs. Expected behavior

Just open the page and type something into the search input.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Thu May 30 21:31:14 PDT 2024; root:xnu-11215.0.31.511.2~1/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Examples

**Comment by fuma-nama** [comment]
We have to wait until Algolia resets, because the search usage exceeded free tier limits.
