### ISSUE TITLE
search not working on vercel with remote content

### ISSUE THREAD

**Issue by Codeize** [fuma-nama/fumadocs#580]
### To Reproduce

1. Follow the guide on remote content using GitHub: https://fumadocs.vercel.app/docs/headless/remote/github
2. Deploy to production on Vercel

### Current vs. Expected behavior

Even whilst running the app in production mode locally, it builds the search index as I expect it to, and then the search functionality itself works as I expect it to.

However, when deploying onto Vercel - according to the build logs - it builds the search index correctly, however when searching for the same content as I did locally it returns no results.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 16307
  Available CPU cores: 16
Binaries:
  Node: 22.2.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.2.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core, MDX

### Additional context

I have altered the setup to remove `/docs` being the root, and instead `/` being the root, as for our use case the docs would be hosted as a separate website to the main website. Albeit unlikely, maybe this has broken something?

**Comment by fuma-nama** [comment]
How do you setup search API? Are you using 3rd party solutions like Algolia Search, or using your own implementation?

**Comment by Codeize** [comment]
I am just using the out-of-the-box solution provided by the remote MDX example, createSearchAPI:
- https://github.com/fuma-nama/fumadocs/blob/dev/examples/remote-mdx/app/api/search/route.ts

**Comment by fuma-nama** [comment]
Don't use that example in production, it's not compatible with serverless runtime. It's just for experimental purposes. As we recommended, use 3rd party solutions like Algolia Search.

Otherwise, using the Fumadocs built-in search, it requires a redeployment when your content changes, which wasted the optimisation of MDX remote.

**Comment by Codeize** [comment]
Alright, thank you.
