### ISSUE TITLE
Unable to import `md` or `mdx` files inside other `mdx` files

### ISSUE THREAD

**Issue by 0sssama** [fuma-nama/fumadocs#586]
### To Reproduce

1. Create a `content/docs/index.mdx` file 
3. Create another `content/docs/_test.mdx` file

```js
// _test.mdx

# Testing

This is a testing file!
```

5. try to import `_test.mdx` file inside the `index.mdx` to include its contents

```js
// index.mdx

import TestingFileContent from './_test.mdx'

<TestingFileContent />
```

6. Start dev server and go to `localhost:3000`, you should see the following error: `Error: await is only valid in async functions and the top level bodies of modules`

## Current behavior

I get an error

## Expected behavior

I should be able to include the contents of `_test.mdx` file inside `index.mdx`. According to [mdx documentation here](https://mdxjs.com/docs/using-mdx/#components):

> Because MDX files are components, they can also import each other:
> ```js
> import License from './license.md' // Assumes an integration is used to compile MDX -> JS.
> import Contributing from './docs/contributing.mdx'
> 
> # Hello world
> 
> <License />
> 
> ---
>
> <Contributing />
> ```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.22
  pnpm: 8.12.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

MDX

**Comment by fuma-nama** [comment]
If you are using Fumadocs MDX, it should work since it's powered by Webpack and we have the same usage in the official docs. I'll need a reproducible example for this

**Comment by 0sssama** [comment]
@fuma-nama I'm using Fumadocs Remote MDX. I will try to create a reproducible example in a minute. Thanks for your help

**Comment by fuma-nama** [comment]
#It doesn't support imports/exports, because we don't use a bundler (same as next-mdx-remote)
