### ISSUE TITLE
Table of Contents has odd overflow behavior 

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#624]
### To Reproduce

When you use an extra-long, one-word heading in your content, the Table of Contents scrolls itself to the right as it tries to accommodate the text content.

### Current vs. Expected behavior

The Table of Contents gets scrolled to the right. I would have expected the Table of Contents to stay to the left side of the container and truncate the text that is too long to fit.

### Provide environment information

```bash
N/A
```

### Which area(s) are affected? (Select all that apply)

UI

### Additional context

![CleanShot 2024-07-22 at 13 36 30@2x](https://github.com/user-attachments/assets/d11231ad-a115-4c8e-9016-f26d8add8eb1)

**Comment by fuma-nama** [comment]
Guess I can set a `overflow-wrap` to it

**Comment by fuma-nama** [comment]
Released a fix ;)
