### ISSUE TITLE
Add section to sources documentation about having different sources for different base URLs

### ISSUE THREAD

**Issue by xhemals** [fuma-nama/fumadocs#626]
### What problem will this feature address?

I am learning how to use fumadocs and i wanted to have my documentation separated as sections weren't related. i.e. instead of having everything in /docs/xxx and using root pages. I wanted it to be so each bit of documentation was on /xxx instead. So i don't need /docs before everything. 

For example. If i have two unrelated bits of documentation: `frontend` and `backend`. Instead of the website url being docs.mycompany.com/docs/frontend and docs.mycompany.com/docs/backend. The urls would be docs.mycompany.com/frontend and docs.mycompany.com/backend. I just didn't like the fact that the url had docs in it twice.

I figured out how to do this myself as there is no documentation for doing this.

### Describe the solution you'd like

I am happy to create documentation on how to do this

### Describe alternatives you've considered

Not adding this (it's an either do or don't thing)

### Additional context

Let me know your thoughts

**Comment by fuma-nama** [comment]
Hmm do you mean having two schema types with different base URLs?
It's documented here: https://fumadocs.vercel.app/docs/mdx/multiple-types

If you mean multiple content sources, it works but is not recommended and you will still have to create another layout for each content source, which isn't ideal in my opinion.

It's the best to have it in our Navigation guide if we can clarify what purpose your section is

**Comment by fuma-nama** [comment]
Also if they are completely unrelated, I personally prefer to have multiple apps in a monorepo (or just separate repo) so it reduces build time for each app

**Comment by fuma-nama** [comment]
Configure Navigation: https://fumadocs.vercel.app/docs/ui/navigation
