### ISSUE TITLE
defaultOpen not working with content-collections

### ISSUE THREAD

**Issue by jonathanwilke** [fuma-nama/fumadocs#632]
### To Reproduce

It seems like the meta property `defaultOpen` for folders is not working when using content-collections.

### Current vs. Expected behavior

Should work.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Thu May 30 21:31:14 PDT 2024; root:xnu-11215.0.31.511.2~1/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
Ensure to update to the latest version of the adapter, it should be fixed recently

**Comment by jonathanwilke** [comment]
Okay, I found out it's not working if I only set it in the meta.json, but if I also set `defaultOpenLevel: 0` in the sidebar options of the DocsLayout, then the items are closed. I think this should probably be controllable only from the meta.json though, right?

**Comment by fuma-nama** [comment]
Oh it was a problem related to the sidebar API, default value of `defaultOpen` is `false` instead of undefined, so the default open level of sidebar will override the `defaultOpen` as it is prior to default value.

**Comment by fuma-nama** [comment]
Fixed
