### ISSUE TITLE
Support draft mode in frontMatter 

### ISSUE THREAD

**Issue by sougouzhinan** [fuma-nama/fumadocs#641]
### What problem will this feature address?

Support draft mode by default 

### Describe the solution you'd like

---
draft: true
---

### Describe alternatives you've considered

Preview draft at development

**Comment by fuma-nama** [comment]
Can you elaborate more about the proposal?

**Comment by fuma-nama** [comment]
At least include the following information in your feature request.
1. What does the feature do?
2. How the syntax would look like?
