### ISSUE TITLE
Empty directory in <Files> does animation when directory is empty

### ISSUE THREAD

**Issue by anthonyshew** [fuma-nama/fumadocs#646]
### To Reproduce

Bubbling this up from https://github.com/vercel/turbo/issues/8859 so we can hopefully take care of it upstream!

### Current vs. Expected behavior

Current: Animation runs, then snaps back to empty state.
Expected: Don't expand downward at all if we know the directory is empty?

### Provide environment information

```bash
N/A
```

### Which area(s) are affected? (Select all that apply)

UI

### Additional context

Might be a tricky one, depending on implementation. 😄

**Comment by fuma-nama** [comment]
Seems like the Radix UI Collapsible component doesn't add the `--radix-collapsible-content-height` CSS variable when it is exactly `0`. I'll fire a bug report to Radix UI and release a fix for this on v13.

**Comment by fuma-nama** [comment]
opened:
https://github.com/radix-ui/primitives/issues/3037

Before they fixed the problem, I'll use Tailwind CSS to define a default value of it.

**Comment by fuma-nama** [comment]
Fixed on v13
