### ISSUE TITLE
OpenAPI Playground: searchParams not being deleted from the URL when set to empty string

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#668]
### To Reproduce

1. Navigate to https://fumadocs.vercel.app/docs/ui/museum/get-museum-hours
2. Paste the Basic token required to make the calls to the API
3. Note a successful 200 response
4. Delete all the query params values under the Query accordion
5. Note the 400 Bad Request response

### Current vs. Expected behavior

Following the steps from the previous section, is expected for the operation to return a 200 OK response with all the data but instead is returning a 400 Bad Request response.
This seems to be caused by an issue in the APIPlayground component where `searchParams` don't get deleted from the URL when they are set to empty strings, causing API calls to fail.

Screen recording:

https://github.com/user-attachments/assets/ddc6e01a-6eb1-40dc-a578-a9e3a68dc9de

PS: As an enhancement (although this might require a separate issue to be open), it would be nice for the URL in the Code Snippets tabs to also reflect the changes in query params.

<img width="984" alt="Screenshot 2024-08-02 at 11 40 18" src="https://github.com/user-attachments/assets/c91da071-4589-4977-bf77-71713ee4e043">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

**Comment by fuma-nama** [comment]
Fixed
