### ISSUE TITLE
Table of contents unable to highlight items near bottom of page

### ISSUE THREAD

**Issue by ZYJLiu** [fuma-nama/fumadocs#670]
### To Reproduce

For example on the fumadocs [quickstart](https://fumadocs.vercel.app/docs/ui) page, when scrolled all the way to the bottom the last highlighted item is Learn More.

![CleanShot 2024-08-02 at 18 18 39@2x](https://github.com/user-attachments/assets/9ed10ff1-003b-4465-bf4d-11d70e17a807)

### Current vs. Expected behavior

Currently the toc is not able to highlight items near bottom of page, while the expected behavior is that the items near the bottom of page still get highlighted when scrolling near bottom of page.

### Provide environment information

```bash
n/a
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
It marks the heading near viewport top as active, I think it's the expected behaviour.

**Comment by ZYJLiu** [comment]
On [this page of the linear docs](https://linear.app/docs/get-the-app), you are able to scroll down to FAQ. Would it be possible to replicate this behavior?

**Comment by fuma-nama** [comment]
Guess they select the heading near the middle of screen instead of top, maybe I can try to reproduce that

**Comment by fuma-nama** [comment]
I believe they added a smart workaround by marking the last heading as active when you scroll to the bottom of page.
There's almost no docs frameworks have a similar behavour, even on Nextra but it won't be difficult to replicate.

**Comment by fuma-nama** [comment]
Released a fix
