### ISSUE TITLE
Searchbar on fumadocs website isn't working

### ISSUE THREAD

**Issue by ZYJLiu** [fuma-nama/fumadocs#677]
### To Reproduce

The searchbar on fumadocs.vercel.app doesn't return any results.

![CleanShot 2024-08-03 at 23 47 28@2x](https://github.com/user-attachments/assets/46e0c0f9-9e82-4afd-b719-5036ed5b29a5)

### Current vs. Expected behavior

Expected behavior is that searchbar returns search results.

### Provide environment information

```bash
n/a
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
That is because it exceeded the limit of Algolia free tier, please wait until August 10
