### ISSUE TITLE
`twoslash include` support

### ISSUE THREAD

**Issue by Yonom** [fuma-nama/fumadocs#685]
### What problem will this feature address?

It would be great to be able to use `twoslash includes main` code blocks that can then be imported into code blocks on the same page :)

### Describe the solution you'd like

<img alt="Screenshot 2024-08-06 at 15 33 17" src="https://github.com/user-attachments/assets/c8958c0d-fcb1-4237-8d73-8c3357134f99" remark-shiki-twoslash height="500">

### Describe alternatives you've considered

-

**Comment by fuma-nama** [comment]
We use Shiki Twoslash: https://twoslash.netlify.app which doesn't seem to support `include`.

See https://github.com/twoslashes/twoslash/issues/47

**Comment by Yonom** [comment]
The includes support seems to have existed as part of remark-shiki-twoslash and that functionality seems to not have been ported to the new package...

Closing this in favor of upstream issue

**Comment by lishaduck** [comment]
Shiki Twoslash now supports includes: shikijs/shiki#737 🎉

**Comment by Yonom** [comment]
Reopening this as upstream support seems to have been added.

I reinstalled `fumadocs-twoslash`, which pulled `@shikijs/twoslash@1.14.1`, yet, I am still receiving the following error:

```
ShikiError: test.mdx:ShikiError: Language `twoslash` not found, you may need to load it first
```

`test.mdx`
````mdx
```twoslash include main
const test = "Hello world!";
```

```tsx twoslash
@include: main
```
````

**Comment by fuma-nama** [comment]
Currently, they didn't document it in the docs (cannot find on their notation reference). But I think your usage is wrong, you should add the language meta, as the error message said.

**Comment by Yonom** [comment]
Oh! my bad, that was an easy fix! 

The following works
`test.mdx`
````mdx
```ts twoslash include main
const test = "Hello world!";
```

```ts twoslash
// @include: main
```
````
