### ISSUE TITLE
Ability to add multiple OpenAPI schema files to `createOpenAPI`

### ISSUE THREAD

**Issue by 0sssama** [fuma-nama/fumadocs#700]
### What problem will this feature address?

Context: https://github.com/fuma-nama/fumadocs/discussions/698

Currently, the `createOpenAPI` method accepts a single OpenAPI schema file in the `documentOrPath` property. In my use case, the OpenAPI schema is split into multiple files and not just one. So, I find myself unable to use the newest version of the `fumadocs-openapi` package in my project.

### Describe the solution you'd like

Have the ability to pass in multiple files to `documentOrPath`, for example:

```js
export const openapi = createOpenAPI({
  // Your OpenAPI Schema (content, url, or path)
  // relative to `cwd`
  documentOrPath: ['./openapi/schema-1.yaml', './openapi/schema-2.yaml', ..... ]
  renderer: { APIPlayground },
});
```

alternatively, it would be a lot more convenient to be able to pass in something like `./openapi/**/*.yaml`

### Describe alternatives you've considered

No alternative has been tried

**Comment by fuma-nama** [comment]
I'm working to support specifying the OpenAPI schema from the `APIPage` component.

**Comment by fuma-nama** [comment]
Should be working now
