### ISSUE TITLE
markdown Image error

### ISSUE THREAD

**Issue by sao-coding** [fuma-nama/fumadocs#702]
### To Reproduce

`![](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*qHtOm0c0IXsefOd2W7VECg.png)`
Using external links will generate

### Current vs. Expected behavior

Show picture

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32656
  Available CPU cores: 12
Binaries:
  Node: 20.15.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
For external images you must specify `width` and `height` for Next.js Image to work
