### ISSUE TITLE
Search functionality  not work on fuma docs

### ISSUE THREAD

**Issue by officialrajdeepsingh** [fuma-nama/fumadocs#717]
### To Reproduce

Go to [https://fumadocs.vercel.app](https://fumadocs.vercel.app)

### Current vs. Expected behavior

checkout current behavior Go to [https://fumadocs.vercel.app](https://fumadocs.vercel.app)

### Provide environment information

```bash
I do not
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by fuma-nama** [comment]
Cannot reproduce your problem, please provide more information
