### ISSUE TITLE
Usage of twoslash + title adds title to code blocks inside hover cards

### ISSUE THREAD

**Issue by Yonom** [fuma-nama/fumadocs#723]
### To Reproduce

````mdx
```ts twoslash title="Test.tsx"
import { ReactNode } from "react";
```
````

### Current vs. Expected behavior

current: all code blocks inside hover cards receive the same title as the outer code block

<div style="display: flex">
<img width="306" alt="Screenshot 2024-08-17 at 23 44 20" src="https://github.com/user-attachments/assets/23e45455-cd3e-4d2c-95a7-84517a62c22f">
<img width="409" alt="Screenshot 2024-08-17 at 23 47 38" src="https://github.com/user-attachments/assets/c302ff84-76d9-4700-9505-418290cd31ba">
</div>

expected: all code blocks inside hover cards should have no title

### Provide environment information

```bash
Node.js v20.15.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.7.1
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Seems like an upstream problem: https://github.com/shikijs/shiki/blob/69b32a33e097231eaf4a0968e78d97b70c0e3f90/packages/twoslash/src/renderer-rich.ts#L242

Guess I'll open a bug report later

**Comment by fuma-nama** [comment]
https://github.com/shikijs/shiki/pull/748

Will be fixed very soon

**Comment by fuma-nama** [comment]
Shiki v1.15.0 has released with inline code support + bug fix

https://github.com/shikijs/shiki/releases/tag/v1.15.0

**Comment by Yonom** [comment]
inline code support is dope! amazing work, thank you!
