### ISSUE TITLE
OpenAPI: Issue rendering the "Path" input when using Common Parameters

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#730]
### To Reproduce

1. Use an OpenAPI schema file that has Common Parameters defined at the path level instead of at the operation level.
```yaml
paths:
  /special-events/{eventId}:
    parameters:
      - $ref: "#/components/parameters/EventId"
    get:
    # ...
```
2. Generate the docs files.

### Current vs. Expected behavior

**Current behaviour:**
There is no "Path" section rendered in the request form, and users are unable to change the path param required for the request.
<img width="572" alt="Screenshot 2024-08-19 at 12 50 02" src="https://github.com/user-attachments/assets/4de086a6-904d-4b9a-b115-60234daf4ea1">

**Expected behaviour:**
There should be a "Path" section rendered in the request form, that expands and reveal a form element to allow users to change the path param.
<img width="572" alt="Screenshot 2024-08-19 at 12 57 58" src="https://github.com/user-attachments/assets/3a27c987-3443-426a-8524-1159e1e5d323">

**Note:**
The "Path" section is rendered only when the parameters are defined at the operation level (inside the `get` object for example).
```yaml
/special-events/{eventId}:
    get:
      summary: Get special event
      # ...
      parameters:
        - $ref: "#/components/parameters/EventId"
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

According to the [documentation](https://swagger.io/docs/specification/describing-parameters/), "in OpenAPI 3.0, parameters are defined in the parameters section of an _operation_ or _path_".

More about [Common Parameters](https://swagger.io/docs/specification/describing-parameters/#common).

**Comment by fuma-nama** [comment]
Should be fixed on Fumadocs OpenAPI 5.3.0
