### ISSUE TITLE
OpenAPI: Schema rendering issues when using `allOf` in `requestBody`

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#736]
### To Reproduce

Reproduction example based off of the museum-api.yaml file.

1. Modify the `/tickets` POST request definition, by using `allOf` in an attempt to override the `ticketType` property defined originally in the `BuyMuseumTicketsRequest` schema.
```yaml
/tickets:
    post:
      summary: Buy museum tickets
      description: Purchase museum tickets for general entry or special events.
      operationId: buyMuseumTickets
      tags:
        - Tickets
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: "#/components/schemas/BuyMuseumTicketsRequest"
                - type: object
                  properties:
                    ticketType:
                      type: string
                      enum:
                        - general
                        - gold
                        - platinum
                        - vip
```
2. Generate the docs.
3. Check the "Request body" section on the related page.

### Current vs. Expected behavior

**Current behavior:**
Even though the `ticketType` property has been correctly overridden, the generate schema is returned as `object & object` with a `body` nested inside another `body` and an unknown `[key: string]` property, which I'm assuming should only be rendered if `additionalProperties` is passed as `true` (see screenshot).
<img width="565" alt="Screenshot 2024-08-22 at 14 30 10" src="https://github.com/user-attachments/assets/d292eb5a-267e-46b8-90db-02402a70707c">

Expected behavior:
The `ticketType` property to be correctly overridden and the Request Body section to be rendered as usual.
<img width="570" alt="Screenshot 2024-08-22 at 14 37 10" src="https://github.com/user-attachments/assets/31821b9b-2d19-4fe0-abec-0258c671ebaf">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.6 // Latest available version is detected (14.2.6).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

Using `allOf` property is a common occurrence in large OpenAPI schema files because it allows users to create common requestBody schemas, which then can have specific properties overridden when referenced in operations or allow those "base schemas" to be extended with other properties only specific to certain path operations.

**Comment by fuma-nama** [comment]
Fixed, you can try it out and see if it has any other problems

**Comment by CosAnca** [comment]
Thank you!
Yes, the reported issue is resolved now but there is another problem now with the properties marked as `required`. They no longer have the `Required` label next to them.
