### ISSUE TITLE
OpenAPI: Save Authorization token in local storage and automatically apply it to future requests

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#740]
### What problem will this feature address?

Navigating to different pages of the OpenAPI generated docs and making requests for each operation requires adding the `Authorization` token into the Authorization form field every time.

### Describe the solution you'd like

A good enhancement would be to save the Authorization token in the local storage of the browser and automatically apply it to any future request. If a new Authorization token is added into the form and a new request is sent, then this new Authorization token value should override the one saved in the local storage.
The saved Authorization token should also be visible in the Authorization form field when navigating to other pages.
<img width="561" alt="Screenshot 2024-08-22 at 17 32 16" src="https://github.com/user-attachments/assets/61afd094-1471-457b-980c-c4eda218107d">

### Describe alternatives you've considered

There don't seem to be any alternatives at the moment to reduce the need to add the Authorization token to every request.

**Comment by fuma-nama** [comment]
Should be supported

**Comment by CosAnca** [comment]
Yes, I confirm it's working as expected.
Thank you!
