### ISSUE TITLE
[Bug] fumadocs-ui package giving MODULE_NOT_FOUND_ERROR 

### ISSUE THREAD

**Issue by SamikshaGarg36** [fuma-nama/fumadocs#742]
This is one of the error message I am receiving:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/samikshagarg/InternshipRepo/Luminum/bot-fe/node_modules/next/dynamic' imported from /Users/samikshagarg/InternshipRepo/Luminum/bot-fe/node_modules/fumadocs-ui/dist/provider.js
Did you mean to import next/dynamic.js?
    at finalizeResolution (node:internal/modules/esm/resolve:255:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/samikshagarg/InternshipRepo/Luminum/bot-fe/node_modules/next/dynamic',
  page: '/docs/test'
}
`

I am using `14.2.6` version of nextjs and latest fumadocs package. This seems to occur not just with `next/dynamic` but most of the imports that don't have `.js` or similar extension in place. What am I doing wrong?

Following up on discussion, I have tested with older versions. 12.2.5 didn't work, but 10.0.1 did.

Small Reproducible repo : https://github.com/SamikshaGarg36/fumadocs-issue

_Originally posted by @SamikshaGarg36 in https://github.com/fuma-nama/fumadocs/discussions/738_

**Comment by fuma-nama** [comment]
Hmm Why are you using Pages Router? It doesn't support server components and we no longer guarantee support for it.

Could you try to migrate to App Router and see if the error still occurs?

**Comment by SamikshaGarg36** [comment]
Hey @fuma-nama ! After Migrating to App Router the error was gone. Thanks. However content collection setup doesn't work

It is giving error :
`Type 'InvalidReturnType<"The return type of the transform function must be an object serializable object.\nSee https://www.content-collections.dev/docs/serialization for more information.\n\nThe following type is not valid:", BaseDoc & { ...; }>' is not assignable to type 'AnyCollection'.
  Type 'InvalidReturnType<"The return type of the transform function must be an object serializable object.\nSee https://www.content-collections.dev/docs/serialization for more information.\n\nThe following type is not valid:", BaseDoc & { ...; }>' is missing the following properties from type 'Omit<CollectionRequest<any, ZodRawShape, "frontmatter" | "json" | "yaml", any, any, any>, "schema">': directory, name, include..` 

[this issue](https://github.com/fuma-nama/fumadocs/issues/571) doesn't help either

**Comment by fuma-nama** [comment]
Seems like some types conflict, you can disable typescript check for now `// @ts-expect-error`

**Comment by fuma-nama** [comment]
Do you mind providing a minimal reproduction? I cannot reproduce the error

**Comment by SamikshaGarg36** [comment]
Hi. You can refer to the same repo : https://github.com/SamikshaGarg36/fumadocs-issue

**Comment by fuma-nama** [comment]
it's because your `test.mdx` contains content that's invalid for your configurations.

Fumadocs official docs uses other remark plugins that might not work with default configurations of Content Collections.

**Comment by SamikshaGarg36** [comment]
Oh yes, Thank you so much for sorting everything!
