### ISSUE TITLE
Load file with dot in the file name. Like v0.1.0.mdx

### ISSUE THREAD

**Issue by RubensKj** [fuma-nama/fumadocs#747]
### What problem will this feature address?

Hello Fuma, how are you doing??

I've created a changelog area in my website and I would love to name my files like `0.1.0.mdx`, `v0.2.0.mdx`.... 

But right now, it seems that the loader does not load those file with a dot

### Describe the solution you'd like

Will be able to load the v0.1.0.mdx file name (names with dot in it)

### Describe alternatives you've considered

In order to work, I just remove the dots from the file and it seems to load normally. But would be nice to load with dots.

### Additional context

Content directory:

- content
   - changelogs
       - project_name
          - v0.1.0.mdx   (if has dots in the name, does not load)
          
          
In case you don't have the time to implemented, I would be able to do it, but I would love some tips where should I start the changes.

**Comment by RubensKj** [comment]
I'm using the `createMDXSource` and `loader`

But once the file has dots, the `utils.getPages()` does not return the files with dots

**Comment by RubensKj** [comment]
I was deep diving into the code and I think I have found the issue. The problem seems to be related with this file method:

https://github.com/fuma-nama/fumadocs/blob/9a72c66bc15e1d297ed9f42843075ce9ba61c8be/packages/core/src/source/path.ts#L24

Maybe we can improve this logic so we can retrieve the locale + file type and also have the ability to load files with dots?
What do you think about it Fuma?

**Comment by fuma-nama** [comment]
Hmm why don't just name it "v0-2-0" instead? It will conflict with our i18n routing

**Comment by RubensKj** [comment]
I've changed the name to be like `v0-2-0` and it works pretty well, thanks for the tip!
Anyways, I think it's a bug not load file with dots. It doesn't throw an error for example. What do you think about it?

---

My suggestion, in order to support files with dots and also load the `.mdx` extension and their location, we can try a different approach to the method logic.

Something like, you split the file name by "." get the last element that will be the extension and the second last part.

A write down a code that might work:

```ts
function extractLocationAndExtension(filename: string): { filename: string, location?: string, extension: string } {
    // Split the filename into parts based on dots
    const parts = filename.split('.');

    // If there's only one part, there's no location or extension
    if (parts.length === 1) {
        return {
            filename: parts[0],
            extension: '',
        };
    }

    // The last part is always the extension
    const extension = parts.pop() as string;

    // The second to last part could be the location or part of the filename
    const locationCandidate = parts.pop();

    let location: string | undefined;
    let baseFilename: string;

    // If the location candidate is a recognized location, treat it as location
    if (locationCandidate && locationCandidate.length === 2) { // assuming location is a two-letter code like 'cn' or 'br'
        location = locationCandidate;
        baseFilename = parts.join('.');
    } else {
        // If not, it's part of the filename
        baseFilename = locationCandidate ? `${parts.join('.')}.${locationCandidate}` : parts.join('.');
    }

    return {
        filename: baseFilename,
        location: location,
        extension: extension,
    };
}
```

Let me know what you think about it?

**Comment by fuma-nama** [comment]
I think it would be better to just ignore numbers locale, I can make a fix soon.
