### ISSUE TITLE
Make OpenApi's DocsDescription a Markdown component

### ISSUE THREAD

**Issue by MorelSerge** [fuma-nama/fumadocs#748]
### What problem will this feature address?

The descriptions currently used in our API description contain markdown syntax. This currently gets rendered without any styling.

### Describe the solution you'd like

Upgrade the `DocsDescription` component to render a Markdown component instead of a normal `p`.

### Describe alternatives you've considered

Not use markdown in the description :)

### Additional context

Redocly has this UI:
![image](https://github.com/user-attachments/assets/d0708707-a24b-40de-9577-307ab5a068fe)
As you can see, you can pretty much enter anything in the description section.

**Comment by MorelSerge** [comment]
This could be fixed by manually rendering the markdown as a child of the `DocsDescription` component.
Any recommended way to recycle the markdown renderer from this package, instead of installing another one?

**Comment by fuma-nama** [comment]
This can be temporally fixed using the `includeDescription  option.

**Comment by fuma-nama** [comment]
It isn't possible with my current design, because Fumadocs OpenAPI doesn't change your `page.tsx`, this ensures other OpenAPI-unrelated pages won't be affected. The `DocsDescription` component is a part of Fumadocs UI and it shouldn't handle markdown.

It expects the content source to handle markdown content, Content Collections works using `transform`, and I'm working on a redesign of Fumadocs MDX to make it possible.

**Comment by fuma-nama** [comment]
I think I'll close this as not planned. consider `ReactMarkdown` and other libraries if you want to render markdown in `DocsDescription`. Or enable `includeDescription` on `generateFiles` to include description as part of the document.

**Comment by lblanch** [comment]
> Or enable `includeDescription` on `generateFiles` to include description as part of the document.

@fuma-nama this was life saving! Thank you! 
I think you should include it in the documentation, at the moment this option is not mentioned in the corresponding section https://fumadocs.vercel.app/docs/ui/openapi/configurations ☺️
