### ISSUE TITLE
Too much spacing when using lists in OpenApi UI

### ISSUE THREAD

**Issue by MorelSerge** [fuma-nama/fumadocs#749]
### To Reproduce

1. Install Fumadocs
2. Set up an OpenAPI UI
3. Use a parameter description with a list element

### Current vs. Expected behavior

Parameter description:
![image](https://github.com/user-attachments/assets/ab1ab284-5e18-4b82-9961-ff1c3bf64d46)
Method description (ok):
![image](https://github.com/user-attachments/assets/5f272a38-303f-4db9-8615-24d0bc576251)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 9.8.0
Relevant Packages:
  next: 14.2.5 // There is a newer version (14.2.6) available, upgrade recommended! 
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: export
 ⚠ There is a newer version (14.2.6) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

Seems like the parameter description rendering renders a bit too much margin. All looks fine in the method description rendered though.

**Comment by MorelSerge** [comment]
I find it similarly awkwardly spaced for just normal paragraphs:
![image](https://github.com/user-attachments/assets/28c8c9d6-4b66-4bb6-90e0-60d7692c5acd)

**Comment by fuma-nama** [comment]
the `description` field is basically for search indexing and OpenGraph/meta tags, it doesn't support markdown (which is why `DocsDescription` doesn't support markdown)

Maybe we can expose an option to add the description to the generated document body? So the MDX loader could handle it as ordinary MDX content
