### ISSUE TITLE
`@fumari/json-schema-to-typescript` seems to be importing a non-existent Prettier method

### ISSUE THREAD

**Issue by ndom91** [fuma-nama/fumadocs#789]
### To Reproduce

In my docs project (https://github.com/gitbutlerapp/gitbutler-docs), I recently updated to the latest versions of all the fumadocs libraries - [open  PR](https://github.com/gitbutlerapp/gitbutler-docs/pull/30). This works in dev, but it's still logging a lot of warnings to the console about an issue when rendering each page for the first time:

> `Critical dependency: the request of a dependency is an expression`

![image](https://github.com/user-attachments/assets/557908f1-fb51-4d8c-9bd1-aff1f8a956ba)

It looks like that use of prettier is compiled to:

```js
import { format as prettify } from "prettier"
function format(code, options) {
  return __async(this, null, function* () {
    if (!options.format) {
      return code;
    }
    return prettify(code, __spreadValues({ parser: "typescript" }, options.style));
  });
}
```

There is a valid exported fn called `format` in the dependent version of `prettier@3.3.3`, so I'm not sunre what the issue here really is :thinking: 

### Current vs. Expected behavior

Current behaviour: Dev mode works, but logs a lot of wanrings to the console each time a page is loaded

Expected behaviour: No additional warnings/errors in console

### Provide environment information

```bash
Node.js v22.4.1

Operating System:
  Platform: linux
  Arch: x64
  Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024
  Available memory (MB): 31607
  Available CPU cores: 14
Binaries:
  Node: 22.4.1
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Core

### Additional context

Not sure if it's' related, but building this code results in a bunch of errors: `ShikiError: debugging.mdx:ShikiError: Must invoke loadWasm first.`

**Comment by fuma-nama** [comment]
It is probably because Prettier uses dynamic import, which Webpack cannot bundle/compile.

**Comment by ndom91** [comment]
Adding the `prettier` I already had in my top-level `package.json` `devDependencies` to the prod `dependencies` isntead seems to have fixed this :+1:

**Comment by ndom91** [comment]
I think it's due to the fact that it only lists `prettier` as a dev dependency [here](https://github.com/fuma-nama/json-schema-to-typescript/blob/master/package.json#L19), but actually requires it at runtime [here](https://github.com/fuma-nama/json-schema-to-typescript/blob/master/packages/json-schema-to-typescript/src/formatter.ts) :thinking: 

What do you think?

**Comment by ndom91** [comment]
My only issue now is that it still doesn't build correctly. It throws this error pointing to a few `mdx` pages with code blocks in them (i.e. ```): `ShikiError: debugging.mdx:ShikiError: Must invoke loadWasm first.`

![image](https://github.com/user-attachments/assets/880328b6-00ea-4cab-bdd4-fe1c59897c3e)

**Comment by fuma-nama** [comment]
Cannot reproduce the problem on CodeSandbox, please open another issue with minimal reproduction provided.

**Comment by ndom91** [comment]
Yup sounds good :+1:
