### ISSUE TITLE
Upgraded to fumadocs 12 -> 13.4; Getting `ShikiError`'s on build

### ISSUE THREAD

**Issue by ndom91** [fuma-nama/fumadocs#795]
### To Reproduce

With [this branch](https://github.com/gitbutlerapp/gitbutler-docs/pull/30) I can no longer build my Fumadocs project.

To reproduce:
1. Clone repo and install deps
2. run `pnpm build`
3. Error

Webpack initial complains about not being able to serialize the error, and then we see the actual error message:

![image](https://github.com/user-attachments/assets/d5e7bfd9-4f52-4808-8dc4-1f2b5826b2ab)

Specifically it's complaining about these files:
- `content/docs/development/debugging.mdx`
- `content/docs/features/virtual-branches/signing-commits.mdx`
- `content/docs/troubleshooting/recovering-stuff.mdx`

These are the only 3 files using ```bash code blocks, so that much makes sense. They're not using any additional highlighting or notation or any feature other than a `title="Terminal"` annotation.

I used your [fumadocs docs site](https://github.com/fuma-nama/fumadocs/tree/dev/apps/docs) as a "template" when upgrading, so the shiki libs I have installed are:

- `shiki@1.16.1`
- `@shikijs/transformers@1.16.1`

Below are my source and source.config files

<details>
<summary><code>app/source.ts</code></summary>

```ts
import { meta, docs } from "@/.source"
import { createMDXSource } from "fumadocs-mdx"
import { loader } from "fumadocs-core/source"
import { attachFile, createOpenAPI } from "fumadocs-openapi/server"
import type { InferMetaType, InferPageType } from "fumadocs-core/source"

export const utils = loader({
  source: createMDXSource(docs, meta),
  pageTree: {
    attachFile
  }
})

export const openapi = createOpenAPI({})

export type Page = InferPageType<typeof utils>
export type Meta = InferMetaType<typeof utils>
```

</details>

<details>
<summary><code>source.config.ts</code></summary>

```ts
import { defineConfig, defineDocs } from "fumadocs-mdx/config"
import remarkYoutube from "remark-youtube"
import { remarkHeading, remarkImage, remarkStructure, rehypeCode } from "fumadocs-core/mdx-plugins"

export const { docs, meta } = defineDocs({
  docs: {}
})

export default defineConfig({
  lastModifiedTime: "git",
  mdxOptions: {
    rehypeCodeOptions: {
      inline: "tailing-curly-colon",
      themes: {
        light: "catppuccin-latte",
        dark: "catppuccin-mocha"
      }
    },
    remarkPlugins: [remarkHeading, remarkImage, remarkStructure, remarkYoutube],
    rehypePlugins: (v) => [rehypeCode, ...v]
  }
})

```

</details>

### Current vs. Expected behavior

Expect to build successfully

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024
  Available memory (MB): 31607
  Available CPU cores: 14
Binaries:
  Node: 22.4.1
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
Fixed on the latest releases, check the closed issue

**Comment by ndom91** [comment]
Awesome works for me, thanks for the quick turnaround :pray:
