### ISSUE TITLE
OpenAPI docs failing on Vercel (missing openapi_spec.json)

### ISSUE THREAD

**Issue by ankrgyl** [fuma-nama/fumadocs#799]
### To Reproduce

For us, just deploying to Vercel reproduces it.

![image](https://github.com/user-attachments/assets/5965c7f1-d9ae-4b3a-843e-8f9635a7ac88)

It appears to have to do with openapi_spec.json not being bundled into the deployment, but since it's supposed to be server-side rendered, does it have to?

### Current vs. Expected behavior

The page should load

### Provide environment information

```bash
fumadocs-openapi@5.4.8
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)

**Comment by fuma-nama** [comment]
See https://fumadocs.vercel.app/docs/ui/openapi/configurations#input

**Comment by ankrgyl** [comment]
Got it, thanks for the tips.
