### ISSUE TITLE
Cannot access DynamicSidebar.then on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.

### ISSUE THREAD

**Issue by donghhan** [fuma-nama/fumadocs#809]
# Reproducing code

## 1. Auto-create project 

Run the command code shown on [documentation](https://fumadocs.vercel.app/docs/ui#automatic-installation)

```bash
npx create-fumadocs-app
```

## 2. Run in dev mode (without touching any NPM packages at all)

```bash
npm run dev
```

### Current vs. Expected behavior

Expected behavior is just to render the example fumadocs UI example correctly, but then when I run in dev mode, I got the following error below: 

```json
Internal error: Error: Cannot access DynamicSidebar.then on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Object.get (/Users/apensia/dev/please-work-shit-man/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:253838)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "1707106195"
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.4.0
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
I've successfully reproduced the problem, Next.js 12.2.8 contains problems on dynamic import with client components. You have to downgrade to 12.2.7 for now

**Comment by donghhan** [comment]
@fuma-nama I am currently using Next.js version of `14.2.8`, which your [auto project creating code](https://fumadocs.vercel.app/docs/ui#automatic-installation) automatically configures. 

Also, Next.js version of `12.2.7` is not available afaik.

**Comment by fuma-nama** [comment]
Oops some typos, set `next` to `14.2.7` on your `package.json` (no `^` prefix).

**Comment by donghhan** [comment]
@fuma-nama Solved the problem. Thank you for help. Closing issue
