### ISSUE TITLE
Cannot read properties of undefined (reading 'collections')

### ISSUE THREAD

**Issue by TheMikeyRoss** [fuma-nama/fumadocs#837]
### To Reproduce

1. Run `pnpm create fumadocs-app` in an existing monorepo
2. run pnpm dev inside the docs workspace
3. see the following error
![image](https://github.com/user-attachments/assets/c7efc7e0-597e-44dc-918a-6dfea4318409)

### Current vs. Expected behavior

`.content-collections` folder was already created, so I think the docs should start normally when I run `pnpm dev`

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 65437
  Available CPU cores: 12
Binaries:
  Node: 21.5.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I didn't touch anything inside the newly created docs.

I simply ran `pnpm create fumadocs-app` and then cd'ed into the docs directory and ran `pnpm dev` and I got the error above

**Comment by TheMikeyRoss** [comment]
I deleted `node_modules` and pnpm-lock and installed it again but got the same issue

**Comment by fuma-nama** [comment]
Probably some upstream issues. Please provide a minimal reproduction

**Comment by Gitstar-OC** [comment]
@TheMikeyRoss  Is the issue solved ? Is your repo that uses fumadocs public ?

**Comment by fuma-nama** [comment]
I’m closing this issue as it cannot be reproduced, please provide a minimal reproduction to this bug report
