### ISSUE TITLE
Support for x-displayName

### ISSUE THREAD

**Issue by MorelSerge** [fuma-nama/fumadocs#862]
### What problem will this feature address?

Using human-readable tag names, instead of the coded ones.

### Describe the solution you'd like

Tags can (with Redocly at least) be augmented with an `x-displayName` value, to give a human-readable value to the tags.

See https://redocly.com/docs/realm/author/reference/openapi-extensions/x-display-name

### Describe alternatives you've considered

N/A

**Comment by fuma-nama** [comment]
Will be supported on Fumadocs v14
