### ISSUE TITLE
Support OpenAPI webhooks

### ISSUE THREAD

**Issue by MorelSerge** [fuma-nama/fumadocs#863]
### What problem will this feature address?

OpenAPI supports defining webhooks:
- 3.1: [spec](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml) & [blog](https://redocly.com/blog/document-webhooks-with-openapi)
- 2.0 & 3.0: [spec](https://redocly.com/docs/api-reference-docs/specification-extensions/x-webhooks)

### Describe the solution you'd like

Would be great to also parse the webhooks in an OpenAPI spec file, adding their pages too.

### Describe alternatives you've considered

N/A

**Comment by fuma-nama** [comment]
the official support is only introduced on OpenAPI 3.1 while Fumadocs OpenAPI is currently 3.0 only.

I plan to migrate it to 3.1 after v14. as we need to fix some other issues before working on the next major release of OpenAPI integration.

**Comment by fuma-nama** [comment]
Supported soon

**Comment by fuma-nama** [comment]
Currently implemented with scalar parser to provide backward compatibility, welcome for feedback as it's relatively a new feature

**Comment by MorelSerge** [comment]
Looks absolute awesome, @fuma-nama.
You're a legend.
