### ISSUE TITLE
Add breadcrumbs to search dialog

### ISSUE THREAD

**Issue by Bartek532** [fuma-nama/fumadocs#866]
### What problem will this feature address?

When using search dialog I encountered an issue when multiple pages are named the same. Then, user won't know which section they belong to. (it's nested page)

![image](https://github.com/user-attachments/assets/5faa1a9f-61b1-476c-8736-035fe907ba51)

### Describe the solution you'd like

Display breadcrumb above page title to easily differentiate it.

### Describe alternatives you've considered

Making my own search dialog? Not sure.

**Comment by fuma-nama** [comment]
I see, as a temporarily fix, if you don’t mind, you can change the passed search index title in route.ts.
Adding the directory name to title could fix the issue for now.

PR welcome

**Comment by fuma-nama** [comment]
I think I'll suggest this solution instead. 

```ts
import { source } from '@/lib/source';
import { createFromSource } from 'fumadocs-core/search/server';
import { getBreadcrumbItems } from 'fumadocs-core/breadcrumb';

export const { GET } = createFromSource(source, (page) => ({
  title: getBreadcrumbItems(page.url, source.pageTree)
    .map((item) => item.name)
    .join(' > '),
  description: page.data.description,
  url: page.url,
  structuredData: page.data.structuredData,
  id: page.url,
}));
```

I normally recommend to not use the same title for different documents, it keeps the search dialog clean since we group results with pages instead of folders.

I have also observed most of the docs sites, almost none of them have a similar design so I decided to not adapt this on Fumadocs UI.

**Comment by Bartek532** [comment]
What is `createFromSource `? I can see only `createSearchAPI`, is it something different?

**Comment by fuma-nama** [comment]
A new API from v14, it's a replacement for create search API, allowing i18n support without changing anything.

**Comment by Bartek532** [comment]
Thanks! I implemented this and got empty title for my `index.tsx` file, which is title "Introduction", shouldn't breadcrumbs work for root file also?

<img width="633" alt="image" src="https://github.com/user-attachments/assets/11fdf748-b761-4eba-ab5c-b628b222e47d">

**Comment by Bartek532** [comment]
> Thanks! I implemented this and got empty title for my `index.tsx` file, which is title "Introduction", shouldn't breadcrumbs work for root file also?
> 
> <img alt="image" width="633" src="https://private-user-images.githubusercontent.com/57185551/369480095-11fdf748-b761-4eba-ab5c-b628b222e47d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDk4MzcsIm5iZiI6MTcyNjg0OTUzNywicGF0aCI6Ii81NzE4NTU1MS8zNjk0ODAwOTUtMTFmZGY3NDgtYjc2MS00ZWJhLWFiNWMtYjYyOGIyMjJlNDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE2MjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZGJkNzQxMWE3ZTJlMmE5YWZkYzI4NTMwYzNlMWRiYjQ4MmIwMjliMmJiOTE4MjgwZmFhMTQyY2Y4NjlkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.de5oqtFIntOivXn9s1v3A1-02c14jjFEhJ6FzPsYXqY">

As you can see it's working for "Extras" so it's an issue for `index.mdx` only 🤔

**Comment by fuma-nama** [comment]
Just use page.data.title if it returned an empty array

**Comment by fuma-nama** [comment]
And thanks for reporting it, fixed it on v14
