### ISSUE TITLE
Ability to always show the top navbar?

### ISSUE THREAD

**Issue by akshatmittal** [fuma-nama/fumadocs#870]
### What problem will this feature address?

I'd like to keep the top nav (full width) on all pages and not just the Home Layout, while using the Sidebar on Docs Layout for navigating between pages.

### Describe the solution you'd like

Sort of a prop on `HomeLayout` to always keep the top nav even in child layouts.

### Describe alternatives you've considered

At the moment, I just have a custom component that I add to the `DocsLayout` pages at the top, but this isn't ideal since it's completely disjoint from the rest of the app.

**Comment by fuma-nama** [comment]
As the major change of Fumadocs v13, I haven't considered to make the previous layout available via options.

As most components are designed for the new layout *only*, it requires some work and I have to lower the effort to maintain our codebase first (e.g. some CSS variables to calculate layout top).

It won't be considered until the v14 release is ready (with completed docs and blog), so we can roll it out as a minor change later.

**Comment by akshatmittal** [comment]
I see, honestly that makes sense. Do you have any idea of when v14 would be ready? I don't want to maintain a fork of Fumadocs if I can avoid it.

**Comment by akshatmittal** [comment]
Got it, so that's at least 2 months away. Thanks for responding!

And just to confirm, you have no intention to enable the layout in the current version because it's going to be quite a bit of work to enable it, right? If so, might just have to maintain a fork for if I do a dirty version.

**Comment by fuma-nama** [comment]
Yes, but also notice that we are doing a major change so breaking changes may happen.

**Comment by akshatmittal** [comment]
Oof, now I don't know what to do 😂

**Comment by akshatmittal** [comment]
Nice, I see it's in the `dev` branch so I'm assuming it's slated for v14.

**Comment by Gitstar-OC** [comment]
I am going to work on this one!

**Comment by nexmoe** [comment]
change your import 'fumadocs-ui/layouts/docs' to 'fumadocs-ui/layouts/notebook'
https://fumadocs.vercel.app/docs/ui/blocks/layout#notebook

![image](https://github.com/user-attachments/assets/26c2a87d-fc67-4d37-8ff9-d29533236426)
