### ISSUE TITLE
Search not working? (flexsearch)

### ISSUE THREAD

**Issue by Bartek532** [fuma-nama/fumadocs#872]
### To Reproduce

1. Visit https://turbostarter.dev/docs/web
2. Click search box to search for something
3. Type one letter like "a" or "e" in search box

### Current vs. Expected behavior

When "web" is chosen nothing is displayed:
![image](https://github.com/user-attachments/assets/44590286-5956-448a-bb7a-78b53bf8d1de)

But when "browser extension" is chosen, then results appear:
![image](https://github.com/user-attachments/assets/ec5f497a-5d02-4363-93e4-2955e7c41a3c)

They have some pages shared, so the same results should appear in both cases.

I'm using Flexsearch, but maybe I should switch to Algolia?

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.9 // There is a newer version (14.2.12) available, upgrade recommended! 
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Core, UI, Content Sources (e.g. Fumadocs MDX, Content Collections), Integrations (e.g OpenAPI, Typescript DocsGen)

**Comment by fuma-nama** [comment]
probably some misspelling on tag names? I need a production for that

**Comment by Bartek532** [comment]
Probably not, as some search phrases are working?
![image](https://github.com/user-attachments/assets/279b945e-700f-4108-9835-c15a3d4ae6e0)

**Comment by fuma-nama** [comment]
![image](https://github.com/user-attachments/assets/f3021d93-104c-40c3-ab40-c3697db7b49e)

I think it's related on how Flexsearch indexes pages, cannot help much on that, especially without the source code of your site.

It requires at least 2 characters from my observations. Since we've migrated to Orama on the dev branch, it's hard to find and fix the problem.

If it's not an urgent matter, I believe Orama doesn't have the same problem.

**Comment by Bartek532** [comment]
Okay, thanks for the explanation, can I migrate to Orama quickly? Or maybe the best will be to migrate to Algolia?

**Comment by fuma-nama** [comment]
Orama migration is a breaking change of Fumadocs v14. For now, you can definitely migrate to Algolia Search, our docs is also using it.

**Comment by Bartek532** [comment]
Okay, thanks for the info, could you tell me when Orama integration is expected to be live?

**Comment by fuma-nama** [comment]
Fumadocs v14 is a big update, probably October/November.

**Comment by fuma-nama** [comment]
Migrated to Orama
