### ISSUE TITLE
Hope to improve i18n content

### ISSUE THREAD

**Issue by inrhor** [fuma-nama/fumadocs#886]
### What problem will this feature address?

I hope to add the corresponding directory, directory structure, and file configuration content under the path.
And I don't quite understand the phrase "move all special files".

### Describe the solution you'd like

My reading ability is limited

### Describe alternatives you've considered

I want to have a directory structure like this
- app
  - [lang]
- xxx

**Comment by fuma-nama** [comment]
If you are new to Next.js, please read their i18n guide first. This is Next.js Routing, not something Fumadocs handles
