### ISSUE TITLE
everything docs/fumadocs related is unstyled on prod

### ISSUE THREAD

**Issue by jeremybosma** [fuma-nama/fumadocs#887]
### To Reproduce

I can't really seem to reproduce since it only happens on prod

### Current vs. Expected behavior

On dev it seems normal on prod the navbar and everything on docs page is unstyled also cmd+k doesnt do anything

### Provide environment information

```bash
jeremy@Jeremys-MacBook-Air docs % bun next info
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23030
      throw new UsageError(`Unsupported package manager specification (${raw})`);
            ^

UsageError: Unsupported package manager specification (bun@1.1.27)
    at parseSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23030:13)
    at loadSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23088:11)
    at async Engine.findProjectSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23262:22)
    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23314:24)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24007:5) {
  clipanion: { type: 'usage' }
}

Node.js v22.1.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:26 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.1.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: 14.2.12
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

### Additional context

https://lapse-docs.vercel.app/

**Comment by fuma-nama** [comment]
Reproduction required

**Comment by jeremybosma** [comment]
okay i guess 

1. https://github.com/uselapse/lapse/invitations accept this read permission stuff
2. run bun install
3. run bun dev
4. go to localhost:3001

**Comment by fuma-nama** [comment]
I think the reason why it's working on dev is that you've cached the result.

![image](https://github.com/user-attachments/assets/cae18b87-be5a-4cd7-ad62-62ee8916a3cb)

Your problem is clearly answer in https://fumadocs.vercel.app/docs/ui#fix-monorepo-styling, the fumadocs-ui package isn't in the node_modules of `apps/docs` which caused Tailwind CSS to fail.
You need to point it to the root `node_modules`

**Comment by jeremybosma** [comment]
tysm
