### ISSUE TITLE
PC端网页缺失翻译按钮

### ISSUE THREAD

**Issue by inrhor** [fuma-nama/fumadocs#895]
### To Reproduce

1、开启i18n为true
![image](https://github.com/user-attachments/assets/92b8f425-1d3f-4639-b881-42653c8a9a05)

2、PC端（电脑）主页Home看不到选择翻译按钮，文档左下角可以看到翻译按钮
![image](https://github.com/user-attachments/assets/ff7fec7d-0701-418b-9a1c-89d69c397f0d)

3、在移除gobal.css后，主页Home看到选择翻译语言按钮
![image](https://github.com/user-attachments/assets/1e9b5942-def6-4614-b4df-07c0d9a3e3a8)

4、移动端（手机）可以看到选择语言按钮

### Current vs. Expected behavior

开启i18n为true，PC端（电脑）主页Home看不到选择翻译按钮

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32478
  Available CPU cores: 12
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by fuma-nama** [comment]
Will be supported on v14
