### ISSUE TITLE
Search does not work correctlly on custom basePath

### ISSUE THREAD

**Issue by MinChanSike** [fuma-nama/fumadocs#899]
### To Reproduce

Hi, searh api does not work as expected if I update custoom basePath of application in **next.config**
It still trying to search on default api path  ```http://localhost:3000/api/search?query=text```

```js
const config = {
  basePath:  "/help",   
  reactStrictMode: true,   
  output: "standalone",
};
export default withMDX(config);
```

### Current vs. Expected behavior

Able to get search result if I try to request this url manually.
```http://localhost:3000/help/api/search?query=text```

### Provide environment information

```bash
Operation System
   Platform: windows
Packages
  "fumadocs-core": "13.4.10", 
  "fumadocs-mdx": "10.0.2",
  "fumadocs-ui": "13.4.10",    
  "next": "^14.2.8",
  "react": "^18.3.1",
```

### Which area(s) are affected? (Select all that apply)

Core

**Comment by fuma-nama** [comment]
You have to update the search route from root provider, see docs for more info.

**Comment by AaronLayton** [comment]
Hiya @fuma-nama I noticed the above url customisation no longer works. Has it moved to somewhere else we can configure?

edit:
I found it 

<img width="458" height="227" alt="Image" src="https://github.com/user-attachments/assets/581f9c4f-6df7-47a5-ab05-2aa59e1ee046" />

Noting that it doesn't seem to work with the custom component though

**Comment by fuma-nama** [comment]
Just pass to the component if you have a custom one

**Comment by nktnet1** [comment]
In my case, for a static Tanstack Start SPA using the default orama search API, I needed to set the `from` property instead of `api`:

```ts
  const searchBasePath = "/example/api/search";

  const { search, setSearch, query } = useDocsSearch({
    client: oramaStaticClient({
      //api: searchBasePath,      // <--- doesn't work
      from: searchBasePath,       // <--- had to set this
      initOrama,
    }),
  });
```

Likewise, the `search.options.api` also doesn't work and can be removed:

```tsx
        <RootProvider
          search={{
            SearchDialog,

            // No longer needed:
            /*
            options: {
              api: "/example/api/search",
            },
            */
          }}
        >
```

See this commit for detail: https://github.com/nktnet1/webview-kiosk/commit/2996fbd8a964a73b74b1472adfe7ac2f00b082f3

**Comment by fuma-nama** [comment]
should be optional soon: https://github.com/fuma-nama/fumadocs/commit/839e3aaa45924730f7e3cc13403ea22b0112e20a
