### ISSUE TITLE
Feat: Make categorizing or organizing pages for docs easier

### ISSUE THREAD

**Issue by Kazooki123** [fuma-nama/fumadocs#905]
### What problem will this feature address?

It will simplify to organize pages with simple strategies or methods to add categories per pages.

### Describe the solution you'd like

Lets say create a library or package that fixes this that includes or touches the folder route system of a docs.

### Describe alternatives you've considered

Nothing yet.

### Additional context

I really want to make my docs have a category, no matter how I try other methods it didn't work. So pls simplify the functions of categorization for organized pages.

**Thank you!**

**Comment by fuma-nama** [comment]
Please elaborate more about the feature. I don't see the reason why not using our current pages convention to organise them
