### ISSUE TITLE
Sort pages in the same category based on meta

### ISSUE THREAD

**Issue by Bartek532** [fuma-nama/fumadocs#919]
### What problem will this feature address?

When I use `DocsCategory` I would expect that displayed cards will be displayed in the same order as in navigation list (based on meta files), but it's sorted alphabetically, how can I improve it?

### Describe the solution you'd like

Built-in support for displaying cards in the same order as it's defined in the meta files.

### Describe alternatives you've considered

Implementing it myself.

**Comment by Bartek532** [comment]
Or maybe there is an easy way to do this with existing utils?

**Comment by fuma-nama** [comment]
> Or maybe there is an easy way to do this with existing utils?

You can do this by traversing the page tree, and match page tree node with their associated pages to obtain additional information that the page tree doesn't provide.

It will be implemented on v14.

**Comment by Bartek532** [comment]
What do you mean by traversing page tree? By using `getNavigationList`?

**Comment by fuma-nama** [comment]
Traverse the tree with your own algorithm, and visit all page nodes in the tree.

**Comment by fuma-nama** [comment]
Supported on v14.

https://fumadocs-dev.vercel.app/blog/v14#better-category-component
