### ISSUE TITLE
Proposal: link to internal doc by id

### ISSUE THREAD

**Issue by songkeys** [fuma-nama/fumadocs#924]
### What problem will this feature address?

There are cases where we reference many internal documents using links such as:

```markdown
Please refer to the [Developer Guide](/docs/developer-guide).
```

However, when files are moved, it becomes challenging to track where these relocated files were referenced in order to update the corresponding links.

### Describe the solution you'd like

I'm thinking about adding a global unique ID to the frontmatter of each document:

```markdown
---
id: developer-guide
title: Developer Guide
description: The guide for developers
---

## ...
```

We can then reference these documents using their IDs:

```markdown
Please refer to the [developer-guide].
```

During the build process, this syntax will automatically convert to:

```markdown
Please refer to the [Developer Guide](/docs/developer-guide).
```

Additionally, we can have a doc link card:

```mdx
Please refer to:

<DocLinkCard id="developer-guide" />
```

which will translate to:

```mdx
Please refer to:

<Card href="/docs/developer-guide" title="Developer Guide" description="The guide for developers" />
```

### Describe alternatives you've considered

N/A

### Additional context

Let me know what you think. I can help work on this.

**Comment by fuma-nama** [comment]
I want to avoid adding additional syntax to Markdown/MDX as much as possible, to keep the migrating experience simple (from other frameworks to Fumadocs, or from Fumadocs to other frameworks), and have no learning cost for authors who only know Markdown or simple MDX.

+ Why don't make and use your own remark/rehype plugin? You can build a community project around that, and Fumadocs's utility can handle that perfectly.

For example, make your custom link/card component wrapper, pass it to MDX components (`MDXContent`). The wrapper takes an `id` prop and find the relevant node with `id` (using `source.getPages()` or your own implementation), and render the card with information of corresponding page.
