### ISSUE TITLE
Anchor Ids for Tabs

### ISSUE THREAD

**Issue by RaniJiang** [fuma-nama/fumadocs#943]
### What problem will this feature address?

Sometimes, I'd like to link users to a specific tab that is not the default. 
E.g. placing form in each tab and asking users to fill out a specific form. 

![image](https://github.com/user-attachments/assets/15548fba-b9b0-406c-9076-4af2daed503d)

### Describe the solution you'd like

Similar to the [Accordion](https://fumadocs.vercel.app/docs/ui/components/accordion#linking-to-accordion) I'd like to be able to use `id` to link to specific tabs as openned. E.g. "/page#tab1" would open the tab with id "tab1".

### Describe alternatives you've considered

- [Default Value/Index](https://fumadocs.vercel.app/docs/ui/components/tabs#default-value) is sufficient if only one form was available at a time to be completed (this can dynamically updated based on the time). 
- Potentially, using the "Radix UI - Primitive" mentioned in [Advanced](https://fumadocs.vercel.app/docs/ui/components/tabs#advanced), apologies I haven't looked into this as much yet! 

Open to other suggestions!

**Comment by fuma-nama** [comment]
Will be supported on v14

**Comment by nktnet1** [comment]
Docs in v14:
https://fumadocs.vercel.app/docs/ui/components/tabs#link-to-tab

![image](https://github.com/user-attachments/assets/38b3240f-cb1e-47a4-8299-703ae715b0f4)

---

Hi @fuma-nama,

Would it be possible to add a "copy link" feature similar to the [Accordion](https://fumadocs.vercel.app/docs/ui/components/accordion#what-is-fumadocs) component?

![image](https://github.com/user-attachments/assets/67befa5d-f7ab-4217-a070-2d8d159beff8)

Or were there some challenges with this approach?

**Comment by fuma-nama** [comment]
You can use accordions which should be a better choice than Tabs, another feature request and PR submission is welcome
