### ISSUE TITLE
Build fails with "Module not found" errors when using fumadocs in edge computing environment

### ISSUE THREAD

**Issue by sukechris** [fuma-nama/fumadocs#950]
### To Reproduce

- Install the latest version of fumadocs
- Set up a Next.js project with fumadocs
- Run next dev - this works without issues
- Run next build - this fails with module not found errors

### Current vs. Expected behavior

Current behavior:
When running next build, the process fails with multiple "Module not found" errors, specifically for 'path' and 'fs' modules. This seems to be related to incompatibility with edge computing platforms.

Expected behavior:
The build process should complete successfully, allowing the application to be deployed on edge computing platforms.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: 8.6.12
Relevant Packages:
  next: 14.2.4 // There is a newer version (14.2.15) available, upgrade recommended!
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
```

### Which area(s) are affected? (Select all that apply)

Core, Integrations (e.g OpenAPI, Typescript DocsGen)

### Additional context

The error seems to be related to packages that are trying to use Node.js specific modules like 'path' and 'fs', which are not available in edge computing environments. The specific packages causing issues are:

- @apidevtools/json-schema-ref-parser
- image-size
- fumadocs-core

The full error message includes:

```bash
../../node_modules/.pnpm/@apidevtools+json-schema-ref-parser@11.7.0/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/util/convert-path-to-posix.js:7:1
Module not found: Can't resolve 'path'

../../node_modules/.pnpm/@apidevtools+json-schema-ref-parser@11.7.0/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/util/url.js:44:1
Module not found: Can't resolve 'path'

../../node_modules/.pnpm/image-size@1.1.1/node_modules/image-size/dist/index.js:4:1
Module not found: Can't resolve 'fs'

../../node_modules/.pnpm/image-size@1.1.1/node_modules/image-size/dist/index.js:5:1
Module not found: Can't resolve 'path'

../../node_modules/.pnpm/image-size@1.1.1/node_modules/image-size/dist/types/tiff.js:6:1
Module not found: Can't resolve 'fs'

```

**Comment by fuma-nama** [comment]
Fumadocs isn’t supposed to work on edge runtime
