### ISSUE TITLE
`createMDX` from `fumadocs-mdx/next` enables `turbo`, breaking rest of my application.

### ISSUE THREAD

**Issue by PhantomKnight287** [fuma-nama/fumadocs#953]
### To Reproduce

Create a nextjs application and follow manual installation to setup fumadocs with fumadocs-mdx. 

### Current vs. Expected behavior

It should allow us to change if we want to enable turbo.

### Provide environment information

```bash
Node.js v20.15.1

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  next: 14.2.14 // There is a newer version (14.2.15) available, upgrade recommended! 
  eslint-config-next: 14.2.14
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Content Sources (e.g. Fumadocs MDX, Content Collections)

### Additional context

My `next.config.mjs`

```ts
import { withNextJSRouteTypes } from "nextjs-route-types";
import { createMDX } from 'fumadocs-mdx/next';

const withMDX = createMDX();
/** @type {import('next').NextConfig} */
const nextConfig = {};

export default withMDX(withNextJSRouteTypes(nextConfig));

```

Logs in terminal:
![image](https://github.com/user-attachments/assets/86986339-d90c-44e6-8266-15eb6a9b91fd)

**Comment by fuma-nama** [comment]
it's only setting options for `turbo`, Turbopack is not enabled unless you use `next dev --turbo`. It's more likely you have made mistakes in your code which causes the error.
