### ISSUE TITLE
Intergrate with shiki-magic-move

### ISSUE THREAD

**Issue by himself65** [fuma-nama/fumadocs#983]
### What problem will this feature address?

https://github.com/shikijs/shiki-magic-move

### Describe the solution you'd like

With https://github.com/shikijs/shiki-magic-move built-in, I can use in MDX and React component

```md
\`\`\`\`md magic-move
\`\`\`ts
1
\`\`\`
\`\`\`ts
2
\`\`\`
\`\`\`\`
```

```tsx
export const Component = () => {
  return (
    <MagicMove>
      <CodeBlock><Pre/></CodeBlock>
      <CodeBlock><Pre/></CodeBlock>
      <CodeBlock><Pre/></CodeBlock>
    </MagicMove>
  )
}
```

### Describe alternatives you've considered

I create a React component manually do this but seems like it not works great, IDK why the font size looks slightly bigger than fumadoc one's

https://github.com/run-llama/LlamaIndexTS/blob/main/apps/next/src/components/magic-move.tsx

**Comment by fuma-nama** [comment]
> I create a React component manually do this but seems like it not works great, IDK why the font size looks slightly bigger than fumadoc one's

Preferably I encourage people to create a React component on their own which gives you more freedom than a tiny wrapper. 

You can set the font size with CSS, I think Shiki works great with it.

Would like to hear the problems you have encountered when creating it

**Comment by himself65** [comment]
First one is theme, I thought fumadoc uses github dark and github light but I create a shiki with them, looks like it's not
Second is font-size, I use default css. left one looks larger

Left: shiki, Right: rumadoc

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/20fa5bb3-f502-4449-b459-b8f7771a57fe">

**Comment by fuma-nama** [comment]
We use vesper theme, and font size is 13/14px

**Comment by himself65** [comment]
Thanks, I hope it's documented!

**Comment by fuma-nama** [comment]
Hmm about integrating Shiki magic moves or the default styles of code blocks? Surely will work on that later

**Comment by himself65** [comment]
I hope there is a global hook useShiki in client side and getShiki in server side. So I don’t need look up what the correct style

**Comment by himself65** [comment]
read the source code seems like this is hard to implement. because it's created inside buildMDX stage

**Comment by fuma-nama** [comment]
I think we will encourage people to create their own component instead for now.

Welcome to bring an example if you have get it working!
