### ISSUE TITLE
emit file `.source/index.js` shoud be `index.mjs`

### ISSUE THREAD

**Issue by himself65** [fuma-nama/fumadocs#988]
### To Reproduce

N/A

### Current vs. Expected behavior

It emits the ESM output, but by default, next.js project is CJS (package.json#module === 'commonjs')

I was writing script in nodejs that will import .source/index.js and realized this

### Provide environment information

```bash
N/A
```

### Which area(s) are affected? (Select all that apply)

Content Sources (e.g. Fumadocs MDX, Content Collections)

**Comment by himself65** [comment]
BTW, I cannot just change package.json to ESM, it have too many side effect to other modules

**Comment by fuma-nama** [comment]
Hmm Next.js has a bundler so having ESM doesn't affect the result. It's not supposed to be read from other runtimes as we relied on the custom loaders of bundlers.

I would suggest a pattern like https://fumadocs.vercel.app/docs/headless/search/algolia#sync-search-indexes to export properties on build, or build your own loader with remark/rehype our MDX plugins. (Can give you details later)

**Comment by himself65** [comment]
Thanks for letting me know. For now I'm customizing the search logic. For now i adhoc one upload script in remarkPlugins

I will migrate to your suggesion

https://github.com/run-llama/LlamaIndexTS/blob/cb51ad90ea71111d21b4dfb3ed5f0a58aff91169/apps/next/source.config.ts#L53-L111

**Comment by fuma-nama** [comment]
Oh for AI training, you can see https://github.com/fuma-nama/fumadocs/blob/dev/apps/docs/scripts/update-orama-ai.mts
