### ISSUE TITLE
feature: add Trieve search support

### ISSUE THREAD

**Issue by densumesh** [fuma-nama/fumadocs#994]
### What problem will this feature address?

This feature will add the ability to use [Trieve](https://trieve.ai) search with fumadocs by building an adapter and sync module for trieve. This has already been implemented in the assistant-ui docs repo with [components/search.tsx](https://github.com/Yonom/assistant-ui/blob/main/apps/docs/components/ui/search.tsx) and [lib/update-index.mjs](https://github.com/Yonom/assistant-ui/blob/main/apps/docs/lib/update-index.mjs). Try it out at [assistant-ui](https://assistant-ui.com)

### Describe the solution you'd like

Build a sync adapter for Trieve as well as a custom search dialog adapter for it. We will take the effort of building this solution as well as adding the documentation for it

### Describe alternatives you've considered

N/A

**Comment by fuma-nama** [comment]
Hmm why don't make a community project instead of merging it into Fumadocs, I think it will be more flexible as I cannot maintain the integration regularly.

**Comment by densumesh** [comment]
Thats fair, we are game to publish a `trieve-fumadocs` package w/ the required modules. We would still like to PR that into the documentation however.

**Comment by fuma-nama** [comment]
Sure!
