### ISSUE TITLE
Unable to load pages with images from github using `fumadocs/mdx-remote`

### ISSUE THREAD

**Issue by minpeter** [fuma-nama/fumadocs#997]
### To Reproduce

https://fumadocs.vercel.app/docs/headless/remote/github
Follow the steps above

The remote content being targeted must contain an image.

### Current vs. Expected behavior

Currently: Unable to render a post with images.   
Expected: Should be able to successfully bundle and fetch remote images and display them.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 10.3.0
  Yarn: 1.22.22
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Content Sources (e.g. Fumadocs MDX, Content Collections)

### Additional context

Are you sure you're using mdx-bundler internally? It would be nice if you could use the esbuildOptions option to bundleMDX.
https://github.com/kentcdodds/mdx-bundler?tab=readme-ov-file#image-bundling
```
    esbuildOptions: (options) => {
      options.minify = true;
      options.loader = {
        ...options.loader,
        '.png': 'dataurl',
        '.jpg': 'dataurl',
        '.gif': 'dataurl',
        '.jpeg': 'dataurl',
        '.webp': 'dataurl',
      };

      return options;
    },
```

**Comment by minpeter** [comment]
![image](https://github.com/user-attachments/assets/a92a7f16-3487-4360-a5d9-cb63deb86c1c)
In basic state

---

If you replace the image component with <img />, the local path will be written to src.

```
  const compiled = await compileMDX({
    source: content,

    components: {
      ...defaultComponents,
      img: (props) => <img {...props} />,
    },
  });
```

**Comment by fuma-nama** [comment]
MDX remote cannot access local file system, you must use an URL instead.
