### ISSUE TITLE
First-party Versioned Docs support

### ISSUE THREAD

**Issue by SukkaW** [fuma-nama/fumadocs#999]
### What problem will this feature address?

Docs for different versions of the same library/software/framework.

Also, not everyone will make full docs versioned, someone might only make parts of the docs i.e. only some categories like integrations or API are versioned. IMHO both should be supported.

### Describe the solution you'd like

Adding version-related fields to the metafile to attach version information.

### Describe alternatives you've considered

We could also do this using a file naming convention. i18n uses suffix (`file.mdx`, `file.en.mdx`), maybe the version could be prefixed (`v1.0.0.file.mdx`, `v1.0.0.file.en.mdx`, `v2.0.0.file.mdx`)?

**Comment by fuma-nama** [comment]
It's not recommended to have different version of docs in the same branch, it increases overall MDX compile time and is often unnecessary. You rarely have a need to update old versions of docs regularly. In this case, version controls like Git works better.

You should deploy and manage different versions with a separate Git branch, so your environment, MDX components, dependencies can work even if your newer docs made changes to them.

See https://fumadocs.vercel.app/docs/ui/navigation#multi-versions

**Comment by SukkaW** [comment]
> It's not recommended to have different version of docs in the same branch, it increases overall MDX compile time and is often unnecessary. You rarely have a need to update old versions of docs regularly. In this case, version controls like Git works better.

The use case is documentation for several integrations/plugins. We have to maintain multiple versions of some integrations (but not others) to support the upstream platform with multiple popular major versions. So we have no choice but to maintain multiple versions of integration together along with almost completely different docs.

> Also, the current functionality of [multiple page tree](https://fumadocs.vercel.app/docs/ui/page-conventions#multiple-page-trees) should suffice your need when it must live under the same branch. I think names like `v2.0.0.file.mdx` is overcomplicated, using root folder + `/<version>/page.mdx` works better.

I am considering this, but a few built-in features (components, hooks, etc.) would be nice.

**Comment by fuma-nama** [comment]
You probably don't need built-in stuff for that, the sidebar tabs component work-out-of-the-box

**Comment by juliusv** [comment]
The various links proposed as solutions in this issue (like https://fumadocs.vercel.app/docs/ui/navigation#multi-versions) don't seem to lead to relevant content anymore, is there anything current about how one would go about multi-version docs? 

I am currently looking for a new docs framework for a modern re-implementation of the https://prometheus.io/ website, and we have two different version selectors there in the sidenav, see https://prometheus.io/docs/prometheus/latest/getting_started/ for the Prometheus server version selector and https://prometheus.io/docs/alerting/latest/overview/ for the Alertmanager version selector, both in the sidebar under their respective nav items. Both of those sub-hierarchies are dynamically assembled from Markdown files in other repositories (prometheus + alertmanager), and at multiple versions. Would something like this be doable in fumadocs with some custom work, or can I forget about that? :)

**Comment by fuma-nama** [comment]
Our recommendations are still same: https://fumadocs.dev/docs/ui#multi-versions

Deploy different versions as a separate app like `v3.tailwindcss.com`. You can link to the docs of other versions using layout links (or anything you want)

**Comment by juliusv** [comment]
Thanks! Ok too bad, that won't work for us unfortunately. That would mean we'd have to maintain ~20 deployments that dynamically change every time there is a new version. So that would mean automating both DNS name management and creating the actual deployment for each version, plus we'd have to redirect old links to the new schema. And the versioning should also only apply to a specific subtree, not the rest of the docs. So definitely not a good fit then 😅

**Comment by fuma-nama** [comment]
> should also only apply to a specific subtree, not the rest of the docs

Then putting the content in a separate folder or tab would be enough, it's not full-site versioning (like Tailwind CSS v3 and v4 site) but more similar to multiple "variants" of a section in your case

**Comment by juliusv** [comment]
> Then putting the content in a separate folder or tab would be enough, it's not full-site versioning (like Tailwind CSS v3 and v4 site) but more similar to multiple "variants" of a section in your case

Correct me if I misunderstand, but are you talking about these kinds of tabs? https://fumadocs.dev/docs/ui/components/tabs . It's a bit difficult to search for "tabs" in the docs because it also finds all the actual tabs used in the docs:

![Image](https://github.com/user-attachments/assets/5c9b2012-50ab-4411-8a16-4799c5bd0842)

I think we will still need an actual dropdown in the two relevant subtrees of the sidenav, as there may be a different set of Markdown docs shown underneath it for each version, so I think it wouldn't be easy to solve with a tab within a document unfortunately. It's ok though, I may have to try to solve this myself using either Astro or NextJS directly I think.

**Comment by fuma-nama** [comment]
The tab is referring to [Sidebar Tabs](https://fumadocs.dev/docs/ui/navigation/sidebar#sidebar-tabs). Tabs are same as folders, but only the opened tab will be visible.

A dropdown component is provided for opening other tabs, just like the official site, but you can also create your component to navigate between tabs.

**Comment by fuma-nama** [comment]
An official guide is now available https://fumadocs.dev/docs/ui/versioning

**Comment by juliusv** [comment]
@fuma-nama Thanks! Yeah, the Sidebar Tabs do look cool. I explored my use case further, and it's unfortunately funky enough that I'm going with a complete custom solution on top of Next.js, but I'm looking forward to trying fumadocs for simpler (non-legacy) future projects :)
